Repository Alfresco/docs-alfresco, pull requests merged in 2021-08, with the labels that each got.

#349 [DOCS-6373] Clean up Using Alfresco Share
  content-services/5.2/using/content/files-folders.md
  content-services/5.2/using/content/index.md
  content-services/5.2/using/content/manage.md
  content-services/5.2/using/content/rules.md
  content-services/5.2/using/dashboard.md
  content-services/5.2/using/index.md
  content-services/5.2/using/permissions.md
  content-services/5.2/using/search.md
  content-services/5.2/using/share.md
  content-services/5.2/using/sites/features.md
  content-services/5.2/using/sites/index.md
  content-services/5.2/using/smart-folders.md
  content-services/5.2/using/tasks.md
Labels: PR: reviewed-approved

#312 Set mutual TLS solr.secureComms=https and port.ssl
  search-services/1.4/install/options.md
Labels: PR: reviewed-approved, search-sie

#350 [DOCS-6383] Rewrite review intro page
  search-enterprise/latest/index.md
Labels: PR: unreviewed
