Repository Alfresco/docs-alfresco, pull requests merged in 2021-05, with the labels that each got.

#231 [DOCS-6246] new rest api
  process-automation/latest/develop/index.md
Labels: PR: partially-approved

#238 DOCS-6034 Cookie based auth
  process-services/latest/config/authenticate.md
Labels: PR: reviewed-approved

#245 DOCS-6077 ReST API Java wrapper and Java API
  _data/toc/content-services.yaml
  content-services/6.0/develop/reference/java-foundation-ref.md
  content-services/6.0/develop/rest-api-guide/audit-apps.md
  content-services/6.1/develop/reference/java-foundation-ref.md
  content-services/6.1/develop/rest-api-guide/audit-apps.md
  content-services/6.2/develop/reference/java-foundation-ref.md
  content-services/6.2/develop/rest-api-guide/audit-apps.md
  content-services/community/develop/reference/java-foundation-ref.md
  content-services/latest/develop/oop-ext-points/rest-api-java-wrapper.md
  content-services/latest/develop/reference/java-foundation-ref.md
  content-services/latest/develop/rest-api-guide/audit-apps.md
  content-services/latest/develop/rest-api-guide/folders-files.md
  content-services/latest/develop/rest-api-guide/people-groups.md
  content-services/latest/develop/rest-api-guide/searching.md
  content-services/latest/develop/rest-api-guide/sites.md
Labels: PR: reviewed-approved

#222 SOLR Default port is 8983 instead of 8080
  search-services/latest/admin/index.md
Labels: PR: reviewed-approved

#248 Fix Customer Support Portal URL
  _includes/footer.html
Labels: PR: reviewed-approved

#246 Fix Recommended Content Documentation
  salesforce/latest/using/recommend.md
Labels: PR: partially-approved

#247 Visualforce page Configuration
  salesforce/latest/install/index.md
Labels: PR: partially-approved

#250 [DOCS-6114] Update supported platforms page
  sync-service/latest/support/index.md
Labels: PR: partially-approved

#253 [DOCS-6260] Correct start/stop script name
  sync-service/3.0/install/options.md
  sync-service/3.1/install/options.md
  sync-service/3.2/install/options.md
  sync-service/3.3/install/options.md
  sync-service/latest/install/options.md
Labels: PR: partially-approved

#237 Pii comprehend and transcribe
  process-automation/images/analysis-process.png
  process-automation/latest/model/connectors/aws.md
Labels: PR: unreviewed

#257 [DOCS-6080] Add property to force the max size for user sync
  desktop-sync/latest/config/index.md
Labels: PR: partially-approved

#259 [DOCS-6268] Update redirects for Desktop Sync
  redirects/desktopsync/tasks/ds-setup-mac.html
  redirects/desktopsync/tasks/ds-setup.html
Labels: PR: reviewed-approved

#255 [DOCS-6075] Add properties to enforce sync
  desktop-sync/latest/admin/index.md
  desktop-sync/latest/config/index.md
Labels: PR: partially-approved

#262 [DOCS-6259] Release summary and consistency updates
  desktop-sync/latest/admin/index.md
  desktop-sync/latest/config/index.md
  desktop-sync/latest/index.md
  desktop-sync/latest/install/index.md
  desktop-sync/latest/support/index.md
  desktop-sync/latest/using/ags.md
  desktop-sync/latest/using/app-icons.md
  desktop-sync/latest/using/app-menu.md
  desktop-sync/latest/using/faq.md
  desktop-sync/latest/using/metadata.md
  desktop-sync/latest/using/permissions.md
  desktop-sync/latest/using/select-to-sync.md
  desktop-sync/latest/using/sharing.md
  desktop-sync/latest/using/sync-conflict-guide.md
Labels: PR: reviewed-approved

#223 [DOCS-6157] APA m12 updates
  process-automation/images/analysis-process.png
  process-automation/latest/admin/monitor.md
  process-automation/latest/admin/release.md
  process-automation/latest/develop/index.md
  process-automation/latest/model/connectors/aws.md
  process-automation/latest/model/connectors/content.md
  process-automation/latest/model/forms.md
  process-automation/latest/model/interfaces.md
  process-automation/latest/model/processes/index.md
  process-automation/latest/model/triggers.md
  process-automation/latest/using/index.md
Labels: PR: reviewed-approved

#254 [DOCS-6134] AGS Community
  governance-services/community/admin/index.md
  governance-services/community/config/index.md
  governance-services/community/develop/index.md
  governance-services/community/install/docker.md
  governance-services/community/install/zip.md
  governance-services/community/upgrade/index.md
  governance-services/community/using/automate-fileplan.md
  governance-services/community/using/easy-access-records.md
Labels: PR: partially-approved

#256 [DOCS-5894] Configuring keystores
  content-services/6.0/admin/security.md
  content-services/6.1/admin/security.md
  content-services/6.2/admin/security.md
  content-services/latest/admin/security.md
Labels: PR: reviewed-approved

#265 [DOCS-6106] Update ACS 7.0 Supported platforms
  content-services/latest/support/index.md
Labels: PR: partially-approved

#266 [DOCS-6274] Fix Google Docs Supported platforms pages
  google-drive/3.1/support/index.md
  google-drive/latest/support/index.md
Labels: PR: reviewed-approved

#271 [DOCS-6277] SP page update for adw 2.2
  content-services/latest/support/index.md
Labels: PR: reviewed-approved

#269 Missing spaces in Spring bean XML
  aws-s3/3.1/config/index.md
  aws-s3/latest/config/index.md
Labels: PR: reviewed-approved

#277 [DOCS-6279] Add SAP Cloud Connector 1.0 to ACS 6.2 SP page
  content-services/6.2/support/index.md
Labels: PR: reviewed-approved

#276 [DOCS-6155] SAP Cloud Connector docs
  sap-cloud/latest/admin/index.md
  sap-cloud/latest/config/index.md
  sap-cloud/latest/install/index.md
Labels: PR: unreviewed

#272 [DOCS-6155] SAP Cloud Connector 1.0
  _config.yml
  _data/home.yaml
  _data/scopes.yaml
  _data/toc/sap-cloud.yaml
  content-services/6.2/support/index.md
  sap-cloud/images/sap_no_license_1.png
  sap-cloud/images/sap_no_license_2_rfc_connection.png
  sap-cloud/images/sap_no_license_3_rfc_connection.png
  sap-cloud/images/sap_oac0_create_cmis_repo.png
  sap-cloud/images/sap_oac0_create_logical_repo.png
  sap-cloud/images/sap_oact_soffdb_category_to_default.png
  sap-cloud/images/sap_se38_cmis_repo_setup_report.png
  sap-cloud/images/sap_se38_cmis_repo_setup_report_result.png
  sap-cloud/images/sap_se38_cmis_repo_setup_report_result_acs.png
  sap-cloud/images/sap_sm59_create_connection.png
  sap-cloud/images/sap_sm59_create_connection_create.png
  sap-cloud/images/sap_sm59_create_connection_create_target_system.png
  sap-cloud/images/sap_sm59_create_connection_create_target_system_logon.png
  sap-cloud/images/sap_sm59_create_connection_create_target_system_test.png
  sap-cloud/images/sap_test_ie03_1.png
  sap-cloud/images/sap_test_ie03_2_acs_view.png
  sap-cloud/images/sap_test_il03_1.png
  sap-cloud/images/sap_test_il03_4_acs_view.png
  sap-cloud/images/sap_test_me23n_4_acs_view.png
  sap-cloud/images/sap_test_mm03_1.png
  sap-cloud/images/sap_test_mm03_2.png
  sap-cloud/images/sap_test_mm03_3.png
  sap-cloud/images/sap_test_mm03_4_acs_view.png
  sap-cloud/latest/admin/index.md
  sap-cloud/latest/config/index.md
  sap-cloud/latest/index.md
  sap-cloud/latest/install/index.md
  sap-cloud/latest/support/index.md
Labels: PR: reviewed-approved
