Repository Alfresco/docs-alfresco, pull requests merged in 2021-04, with the labels that each got.

#193 [DOCS-6220] query accelerator adjustment
  content-services/latest/admin/query-accelerator.md
Labels: PR: partially-approved

#196 [DOCS-6221] Add Send and Archive info in Outlook
  microsoft-outlook/images/2-8-ribbon-top.png
  microsoft-outlook/images/2-8-ribbon.png
  microsoft-outlook/latest/config/index.md
  microsoft-outlook/latest/using/index.md
Labels: PR: reviewed-approved

#202 [DOCS-6108] Misc config fixes - tokenAlterMode and ADF links
  microsoft-outlook/latest/config/index.md
Labels: PR: unreviewed

#201 [DOCS-6224] Add ability to use wildcards for metadata
  microsoft-outlook/latest/config/index.md
Labels: PR: reviewed-approved

#198 [DOCS-6222] Add Uploading complete folders feature in Outlook
  microsoft-outlook/latest/config/index.md
  microsoft-outlook/latest/install/index.md
  microsoft-outlook/latest/using/index.md
Labels: PR: unreviewed

#212 [DOCS-6229] Update support status in ADW 2.1 and standardize table
  digital-workspace/1.5/support/index.md
  digital-workspace/1.6/support/index.md
  digital-workspace/2.0/support/index.md
  digital-workspace/latest/support/index.md
Labels: PR: reviewed-approved

#197 [DOCS-6227] Correct SP pages for ACS 7 compatible releases
  google-drive/latest/support/index.md
  insight-engine/latest/support/index.md
  salesforce/latest/support/index.md
  saml-module/latest/support/index.md
  sap/latest/support/index.md
  search-services/latest/support/index.md
Labels: PR: partially-approved

#208 [DOCS-6214] Identity service 1.4 keycloak references updates
  identity-service/1.0/index.md
  identity-service/1.1/index.md
  identity-service/1.2/config/index.md
  identity-service/1.2/index.md
  identity-service/1.2/upgrade/index.md
  identity-service/latest/config/index.md
  identity-service/latest/index.md
  identity-service/latest/tutorial/sso/saml.md
  identity-service/latest/upgrade/index.md
Labels: PR: reviewed-approved

#206 Link conversion fixed
  search-services/latest/install/index.md
Labels: PR: reviewed-approved

#207 SEARCH-2747 Rephase using 'we' rather than 'I' for consistency with surrounding page.
  _archive/content-services/5.2/concepts/dev-api-by-language-alf-rest-finding-content-by-search-query.md
  content-services/6.0/develop/rest-api-guide/searching.md
  content-services/6.1/develop/rest-api-guide/searching.md
  content-services/6.2/develop/rest-api-guide/searching.md
  content-services/community/develop/rest-api-guide/searching.md
  content-services/latest/develop/rest-api-guide/searching.md
Labels: PR: reviewed-approved

#217 Property changed for Solr4/6
  search-services/latest/config/properties.md
Labels: PR: reviewed-approved

#200 [DOCS-6223] Add Aspect type mapping
  microsoft-outlook/latest/config/index.md
Labels: PR: reviewed-approved

#219 [DOCS-6221] Fix Send and Archive default folder option
  microsoft-outlook/latest/config/index.md
Labels: PR: partially-approved

#221 [DOCS-6240] Update supported platforms for Outlook 2.8
  microsoft-outlook/latest/install/index.md
  microsoft-outlook/latest/support/index.md
Labels: PR: partially-approved

#224 [DOCS-6149] Add SDK 4.2 to ACS 7 Supported platforms page
  content-services/latest/support/index.md
Labels: PR: reviewed-approved

#227 [DOCS-6108] Add feature summary for v2.8 release
  microsoft-outlook/latest/index.md
  microsoft-outlook/latest/using/index.md
Labels: PR: partially-approved

#216 [DOCS-6204] Add T-Engine to Outlook installation
  microsoft-outlook/latest/install/index.md
  microsoft-outlook/latest/support/index.md
Labels: PR: partially-approved

#229 [DOCS-6129] Change SAP license name
  sap/5.0/install/index.md
  sap/latest/install/index.md
Labels: PR: reviewed-approved

#226 [DOCS-6237] Public Java API
  _data/toc/content-services.yaml
  content-services/6.0/develop/reference/java-foundation-ref.md
  content-services/6.1/develop/reference/java-foundation-ref.md
  content-services/6.2/develop/reference/java-foundation-ref.md
  content-services/community/develop/reference/java-foundation-ref.md
  content-services/latest/develop/oop-ext-points/rest-api-java-wrapper.md
  content-services/latest/develop/reference/java-foundation-ref.md
Labels: PR: reviewed-approved

#220 [DOCS-6111] Ux images added to ais 1.3
  intelligence-services/images/pii.png
  intelligence-services/images/text-transcript.png
  intelligence-services/images/transcript-caption.png
  intelligence-services/latest/admin/troubleshoot.md
  intelligence-services/latest/using/index.md
Labels: PR: partially-approved

#233 [DOCS-6235] Update redirects for Support Handbook
  redirects/support/concepts/su-product-policy.html
  redirects/support/concepts/su-resources.html
  redirects/support/concepts/su-support-policies.html
  redirects/support/concepts/su-welcome.html
  redirects/support/ditamaps/index.html
  redirects/support/reuse/copyright.html
Labels: PR: reviewed-approved

#225 Typo
  content-services/community/admin/workflows.md
Labels: PR: reviewed-approved

#234 Fix typos in various pages
  content-services/6.0/admin/audit.md
  content-services/6.0/admin/workflows.md
  content-services/6.1/admin/audit.md
  content-services/6.1/admin/workflows.md
  content-services/6.2/admin/audit.md
  content-services/6.2/admin/workflows.md
  content-services/community/admin/audit.md
  content-services/community/admin/workflows.md
  content-services/latest/admin/audit.md
  content-services/latest/admin/workflows.md
Labels: PR: reviewed-approved

#232 [DOCS-6250] APA process visualization improved
  process-automation/latest/model/processes/index.md
Labels: PR: partially-approved

#235 [DOCS-6252]Task notification in adw
  process-automation/latest/using/index.md
Labels: PR: partially-approved
