Repository Alfresco/docs-alfresco, pull requests merged in 2021-03, with the labels that each got.

#149 [DOCS-6163] Correct version of APS Action AMP file
  content-services/latest/config/action.md
Labels: PR: reviewed-approved

#150 [DOCS-6164] Update APS Action version for 7.0
  content-services/latest/config/action.md
Labels: PR: reviewed-approved

#141 Update to clarify deployment policy
  _data/toc/support.yaml
  process-services/1.10/install/container.md
  process-services/latest/install/container.md
  support/latest/policies/containerization.md
  support/latest/policies/deployment.md
Labels: PR: partially-approved

#158 [DOCS-6177] Fix redirects for 6.x Supported Platforms pages
  content-services/latest/index.md
  redirects/6.0/concepts/supported-platforms-ACS.html
  redirects/6.1/concepts/supported-platforms-ACS.html
  redirects/6.2/concepts/supported-platforms-ACS.html
Labels: PR: reviewed-approved

#157 [DOCS-6173] Update containerized deployment messaging for 7.0 & Community
  content-services/community/install/containers/docker-compose.md
  content-services/community/install/containers/index.md
  content-services/latest/install/containers/docker-compose.md
  content-services/latest/install/containers/index.md
Labels: PR: unreviewed

#160 DOCS-6069 DOCS-6079
  salesforce/latest/install/index.md
Labels: PR: reviewed-approved

#154 [DOCS-6170] add extension inspector
  _data/toc/content-services.yaml
  content-services/latest/develop/extension-inspector.md
Labels: PR: reviewed-approved

#161 [DOCS-6185] Fix in-product redirects
  redirects/desktopsync/concepts/desktopsync-using-mac.html
  redirects/desktopsync/tasks/ds-setup-mac.html
  redirects/desktopsync/tasks/ds-setup.html
  redirects/desktopsync1.0/concepts/desktopsync-using-mac.html
  redirects/desktopsync1.0/concepts/desktopsync-using.html
  redirects/desktopsync1.0/tasks/ds-setup-mac.html
  redirects/desktopsync1.1/concepts/desktopsync-using-mac.html
  redirects/desktopsync1.1/tasks/ds-setup.html
  redirects/desktopsync1.2/concepts/desktopsync-using-mac.html
  redirects/desktopsync1.2/tasks/ds-setup.html
  redirects/desktopsync1.3/concepts/desktopsync-using-mac.html
  redirects/desktopsync1.3/tasks/ds-setup.html
  redirects/desktopsync1.4/concepts/desktopsync-using-mac.html
  redirects/desktopsync1.4/tasks/ds-setup.html
  redirects/desktopsync1.5/concepts/desktopsync-using-mac.html
  redirects/desktopsync1.5/tasks/ds-setup.html
  redirects/salesforce/concepts/salesforce-ent-repo-tab.html
  redirects/salesforce/tasks/salesforce-ent-add-site.html
  redirects/salesforce2.0/concepts/salesforce-ent-repo-tab.html
  redirects/salesforce2.0/tasks/salesforce-ent-add-site.html
  redirects/salesforce2.1/concepts/salesforce-ent-repo-tab.html
  redirects/salesforce2.1/tasks/salesforce-ent-add-site.html
  redirects/support/concepts/su-containerization-policy.html
Labels: PR: reviewed-approved

#166 [DOCS-6188] UA review for Extension Inspector
  content-services/latest/develop/extension-inspector.md
Labels: PR: unreviewed

#151 [DOCS-6091] Add new parameters for scheduled jobs
  content-services/latest/develop/repo-ext-points/scheduled-jobs.md
Labels: PR: reviewed-approved

#170 [DOCS-6082] Query accelerator admin addition
  _data/toc/content-services.yaml
  content-services/images/acs-aspects.png
  content-services/images/acs-properties.png
  content-services/images/admin-console-menu.png
  content-services/images/query-set-not-removed.png
  content-services/images/query-set-removed.png
  content-services/images/refresh-query-set-not-started.png
  content-services/images/refresh-query-set-started.png
  content-services/images/refresh-query-set.png
  content-services/images/remove-query-set.png
  content-services/latest/admin/query-accelerator.md
Labels: PR: reviewed-approved

#163 [DOCS-6123] ATS 1.3.2
  transform-service/images/ats-1.3.2-components.png
  transform-service/images/ats-1.3.2-containerized-deployment.png
  transform-service/latest/admin/index.md
  transform-service/latest/config/index.md
  transform-service/latest/index.md
  transform-service/latest/install/index.md
  transform-service/latest/support/index.md
Labels: PR: unreviewed

#144 [DOCS-6082] query accelerator
  _config.yml
  _data/home.yaml
  _data/scopes.yaml
  _data/toc/query-accelerator.yaml
  query-accelerator/images/acs-aspects.png
  query-accelerator/images/acs-properties.png
  query-accelerator/images/admin-console-menu.png
  query-accelerator/images/query-set-not-removed.png
  query-accelerator/images/query-set-removed.png
  query-accelerator/images/refresh-query-set-not-started.png
  query-accelerator/images/refresh-query-set-started.png
  query-accelerator/images/refresh-query-set.png
  query-accelerator/images/remove-query-set.png
  query-accelerator/latest/config/index.md
  query-accelerator/latest/index.md
  query-accelerator/latest/install/index.md
  query-accelerator/latest/support/index.md
  query-accelerator/latest/using/index.md
Labels: PR: reviewed-approved

#169 Helm chart update (Replaces Gavin's PR-#167)
  content-services/6.0/install/containers/helm.md
  content-services/6.1/install/containers/helm-examples.md
  content-services/6.1/install/containers/helm.md
  content-services/6.2/install/containers/helm-examples.md
  content-services/6.2/install/containers/helm.md
  content-services/latest/install/containers/helm-examples.md
  content-services/latest/install/containers/helm.md
Labels: PR: partially-approved

#162 [DOCS-6112] Removal of Legacy transforms and moving metadata to T-Engines
  _data/toc/content-services.yaml
  content-services/latest/admin/admin-console.md
  content-services/latest/admin/jmx-reference.md
  content-services/latest/admin/metadata-extraction.md
  content-services/latest/admin/transformations.md
  content-services/latest/admin/troubleshoot.md
  content-services/latest/config/index.md
  content-services/latest/config/libreoffice.md
  content-services/latest/config/repository.md
  content-services/latest/config/subsystems.md
  content-services/latest/develop/repo-ext-points/content-transformers-renditions.md
  content-services/latest/develop/repo-ext-points/metadata-extractors.md
  content-services/latest/develop/sdk.md
  content-services/latest/install/zip/additions.md
Labels: PR: unreviewed

#171 Revert "[DOCS-6082] query accelerator"
  _config.yml
  _data/home.yaml
  _data/scopes.yaml
  _data/toc/query-accelerator.yaml
  query-accelerator/images/acs-aspects.png
  query-accelerator/images/acs-properties.png
  query-accelerator/images/admin-console-menu.png
  query-accelerator/images/query-set-not-removed.png
  query-accelerator/images/query-set-removed.png
  query-accelerator/images/refresh-query-set-not-started.png
  query-accelerator/images/refresh-query-set-started.png
  query-accelerator/images/refresh-query-set.png
  query-accelerator/images/remove-query-set.png
  query-accelerator/latest/config/index.md
  query-accelerator/latest/index.md
  query-accelerator/latest/install/index.md
  query-accelerator/latest/support/index.md
  query-accelerator/latest/using/index.md
Labels: PR: reviewed-approved

#147 [DOCS-6133] Update Upgrade pages for ACS 7.0
  content-services/community/upgrade/index.md
  content-services/images/upgrade-path-7-0.png
  content-services/latest/upgrade/index.md
Labels: PR: reviewed-approved

#152 [DOCS-6131] Add Ansible deployment
  _data/toc/content-services.yaml
  content-services/community/install/ansible.md
  content-services/images/acs-localhost.png
  content-services/images/acs-multi-machine.png
  content-services/images/acs-single-machine.png
  content-services/images/centos-ami.png
  content-services/images/deployment-type-local.png
  content-services/images/deployment-type-ssh.png
  content-services/latest/install/ansible.md
Labels: PR: unreviewed

#164 [DOCS-6147] Securing installation [Docs 6135] Reference to security (keystores) during installation
  _data/toc/content-services.yaml
  content-services/images/acs-protocol-overview-inbound.png
  content-services/images/acs-protocol-overview-outbound.png
  content-services/images/acs-secure-comms-repo-solr-keystores.png
  content-services/images/acs-security-checklist.png
  content-services/images/acs-security-overview.png
  content-services/latest/admin/securing-install.md
  content-services/latest/admin/security.md
  content-services/latest/config/index.md
  content-services/latest/install/containers/helm.md
  content-services/latest/install/index.md
  content-services/latest/install/zip/index.md
  content-services/latest/install/zip/tomcat.md
  insight-engine/latest/config/keys.md
  search-services/latest/config/keys.md
Labels: PR: unreviewed

#153 [DOCS-6132] Update Installation overview page
  content-services/community/install/index.md
  content-services/images/acs-typical-installation-community.png
  content-services/images/acs-typical-installation.png
  content-services/latest/install/index.md
Labels: PR: partially-approved

#173 [DOCS-6190] Fix links to new content
  _data/toc/content-services.yaml
  content-services/community/install/index.md
  content-services/latest/install/ansible.md
  content-services/latest/install/index.md
  content-services/latest/upgrade/index.md
Labels: PR: reviewed-approved

#176 [DOCS-6191] Add Extension Inspector to Community docs
  _data/toc/content-services.yaml
  content-services/community/develop/extension-inspector.md
Labels: PR: reviewed-approved

#179 [DOCS-6201] Update Docker Compose steps
  content-services/community/install/containers/docker-compose.md
  content-services/latest/install/containers/docker-compose.md
Labels: PR: reviewed-approved

#182 [DOCS-6212] Clean up version numbers in 7.0 docs
  content-services/latest/admin/auth-sync.md
  content-services/latest/admin/cluster.md
  content-services/latest/admin/db-cleanup.md
  content-services/latest/admin/import-transfer.md
  content-services/latest/admin/security.md
  content-services/latest/config/index.md
  content-services/latest/config/repository.md
  content-services/latest/config/smart-folders/index.md
  content-services/latest/develop/reference/aikau-intro-ref.md
  content-services/latest/develop/rest-api-guide/install.md
  content-services/latest/install/containers/helm.md
  content-services/latest/install/containers/index.md
  content-services/latest/install/zip/amp.md
  content-services/latest/install/zip/index.md
  content-services/latest/install/zip/tomcat.md
  content-services/latest/tutorial/share/doclib.md
Labels: PR: partially-approved

#183 [DOCS-6202] Update Admin Console summary
  content-services/latest/admin/admin-console.md
Labels: PR: reviewed-approved

#184 [DOCS-6203] Minor updates for ACS 7 docs
  content-services/latest/index.md
  content-services/latest/support/index.md
Labels: PR: reviewed-approved

#185 [DOCS-6195] Update Ansible pages
  content-services/community/install/ansible.md
  content-services/latest/install/ansible.md
Labels: PR: partially-approved

#186 Add Amazon Corretto
  content-services/latest/support/index.md
Labels: PR: reviewed-approved

#175 Update securing-install.md
  content-services/latest/admin/securing-install.md
Labels: PR: partially-approved

#180 [DOCS-6197]-Transform and Metadata changes applied to Community
  _data/toc/content-services.yaml
  content-services/community/admin/metadata-extraction.md
  content-services/community/admin/transformations.md
  content-services/community/config/index.md
  content-services/community/config/libreoffice.md
  content-services/community/config/repository.md
  content-services/community/config/subsystems.md
  content-services/community/develop/repo-ext-points/content-transformers-renditions.md
  content-services/community/develop/repo-ext-points/metadata-extractors.md
  content-services/community/develop/sdk.md
  content-services/community/install/zip/additions.md
  content-services/latest/config/index.md
  content-services/latest/develop/repo-ext-points/content-transformers-renditions.md
  content-services/latest/develop/repo-ext-points/metadata-extractors.md
  content-services/latest/install/zip/additions.md
Labels: PR: unreviewed

#188 [DOCS-6215] Fix redirect for Download Trial
  redirects/trial/concepts/download-intro.html
  redirects/trial/ditamaps/index.html
  redirects/trial/tasks/deploy-docker-compose.html
Labels: PR: reviewed-approved

#187 Misc site improvements
  _includes/footer.html
  _layouts/docs.html
  content-services/6.0/index.md
  content-services/6.1/index.md
  content-services/6.2/index.md
  content-services/community/index.md
  content-services/latest/index.md
  terms.md
Labels: PR: reviewed-approved

#190 [DOCS-6218] Merge latest Content Services updates
  _data/toc/content-services.yaml
  _includes/footer.html
  _layouts/docs.html
  content-services/6.0/index.md
  content-services/6.1/index.md
  content-services/6.2/index.md
  content-services/community/admin/metadata-extraction.md
  content-services/community/admin/transformations.md
  content-services/community/config/index.md
  content-services/community/config/libreoffice.md
  content-services/community/config/repository.md
  content-services/community/config/subsystems.md
  content-services/community/develop/extension-inspector.md
  content-services/community/develop/repo-ext-points/content-transformers-renditions.md
  content-services/community/develop/repo-ext-points/metadata-extractors.md
  content-services/community/develop/sdk.md
  content-services/community/index.md
  content-services/community/install/ansible.md
  content-services/community/install/containers/docker-compose.md
  content-services/community/install/zip/additions.md
  content-services/latest/admin/admin-console.md
  content-services/latest/config/index.md
  content-services/latest/develop/repo-ext-points/content-transformers-renditions.md
  content-services/latest/develop/repo-ext-points/metadata-extractors.md
  content-services/latest/index.md
  content-services/latest/install/ansible.md
  content-services/latest/install/containers/docker-compose.md
  content-services/latest/install/zip/additions.md
  content-services/latest/support/index.md
  terms.md
Labels: PR: reviewed-approved

#191 Fix redirect for desktopsync-using-mac.html
  redirects/desktopsync/concepts/desktopsync-using-mac.html
Labels: PR: reviewed-approved

#181 [DOCS-6122] Mobile workspace
  _config.yml
  _data/home.yaml
  _data/scopes.yaml
  _data/toc/mobile-workspace.yaml
  mobile-workspace/latest/config/index.md
  mobile-workspace/latest/index.md
  mobile-workspace/latest/using/index.md
Labels: PR: reviewed-approved

#194 [DOCS-6108] Update artefacts and Supported platforms
  microsoft-outlook/latest/config/index.md
  microsoft-outlook/latest/install/index.md
  microsoft-outlook/latest/support/index.md
Labels: PR: unreviewed
