Repository Alfresco/docs-alfresco, pull requests merged in 2021-07, with the labels that each got.

#309 [DOCS-6287] Admins can configure what users can not see or sync
  desktop-sync/latest/admin/index.md
  desktop-sync/latest/config/index.md
  desktop-sync/latest/index.md
Labels: PR: partially-approved

#281 [MNT-22392] Docs update to address CVE-2020-13941
  search-services/1.4/config/properties.md
  search-services/1.4/config/security.md
  search-services/latest/config/properties.md
  search-services/latest/config/security.md
Labels: PR: reviewed-approved

#209 MNT-22060 Add note that Java 11.0.9.1 will not work with Search Services or Insight Engine.
  content-services/6.0/support/index.md
  content-services/6.1/support/index.md
  content-services/6.2/support/index.md
  content-services/latest/support/index.md
  insight-engine/1.4/support/index.md
  insight-engine/latest/support/index.md
Labels: PR: unreviewed

#314 [DOCS-6189] Add Ansible page for 6.2
  _data/toc/content-services.yaml
  content-services/6.2/install/ansible.md
Labels: PR: reviewed-approved

#288 [DOCS-6265] Debugging Content Services
  _data/toc/content-services.yaml
  content-services/images/acs-debug-idea-breakpoint-set.png
  content-services/images/acs-debug-idea-create-ticket.png
  content-services/images/acs-debug-idea-session-started.png
  content-services/images/acs-debug-idea-settings.png
  content-services/latest/develop/oop-sdk.md
  content-services/latest/develop/reference/debugging-ref.md
  content-services/latest/develop/sdk.md
Labels: PR: reviewed-approved

#305 [MNT-22173] Update Salesforce Connector SSO Documentation
  salesforce/2.2/config/index.md
  salesforce/latest/config/index.md
Labels: PR: partially-approved

#315 [DOCS-6328] Fix version numbers in Support Handbook pages
  _layouts/docs.html
Labels: PR: reviewed-approved

#322 [DOCS-6307] Fix T-Engine steps for Outlook Integration 2.8
  microsoft-outlook/latest/install/index.md
Labels: PR: reviewed-approved

#295 [DOCS-6110] adjustments to supported versions of office
  transformation-engine/latest/install/index.md
Labels: PR: partially-approved

#311 [DOCS-6249] Updates for SAP Cloud Connector 1.1 docs
  _data/toc/sap-cloud.yaml
  sap-cloud/images/sap_btp_destination.png
  sap-cloud/images/sap_cloud_add_attachment_1.png
  sap-cloud/images/sap_cloud_add_attachment_2_draft.png
  sap-cloud/images/sap_cloud_add_attachment_2_draft_alfresco.png
  sap-cloud/images/sap_cloud_add_attachment_2_final.png
  sap-cloud/images/sap_cloud_add_attachment_2_final_alfresco.png
  sap-cloud/images/sap_cloud_manage_product_master_data.png
  sap-cloud/images/sap_cloud_troubleshooting_error_upload.png
  sap-cloud/latest/admin/index.md
  sap-cloud/latest/config/cloud.md
  sap-cloud/latest/config/index.md
  sap-cloud/latest/index.md
  sap-cloud/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#326 Revert "[DOCS-6110] adjustments to supported versions of office"
  transformation-engine/latest/install/index.md
Labels: PR: unreviewed

#327 [DOCS-6315] corrections for revert
  transformation-engine/latest/install/index.md
Labels: PR: reviewed-approved

#328 [DOCS-6245] Add properties to manage sync configuration
  desktop-sync/latest/admin/index.md
  desktop-sync/latest/config/index.md
Labels: PR: partially-approved

#329 [DOCS-6325] Add Alfresco Content Connector for SAP Cloud 1.1 to ACS SP pages
  content-services/6.2/support/index.md
  content-services/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#317 [DOCS-6269] Search services performance recommendations
  _data/toc/insight-engine.yaml
  _data/toc/search-services.yaml
  insight-engine/latest/admin/index.md
  insight-engine/latest/config/performance.md
  search-services/latest/admin/index.md
  search-services/latest/config/performance.md
Labels: PR: partially-approved

#332 Changes to ES examples
  process-services/1.11/develop/dev-ext.md
Labels: PR: reviewed-approved

#330 [DOCS-6335] Indexing recommendations
  _data/toc/insight-engine.yaml
  _data/toc/search-services.yaml
  insight-engine/latest/config/indexing.md
  search-services/latest/config/indexing.md
Labels: PR: unreviewed

#335 [DOCS-6323] Add SAML 1.2.2 to ACS 7 SP page
  content-services/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#323 [DOCS-6241] CMIS API Restore / Migrate
  _data/toc/content-services.yaml
  content-services/5.2/develop/apis-by-function.md
  content-services/5.2/develop/cmis-api-guide.md
  content-services/5.2/develop/platform-integrations.md
  content-services/5.2/develop/reference/cmis-ref.md
  content-services/5.2/develop/rest-api-guide/index.md
  content-services/6.0/develop/reference/cmis-ref.md
  content-services/6.1/develop/reference/cmis-ref.md
  content-services/6.2/develop/reference/cmis-ref.md
  content-services/community/develop/reference/cmis-ref.md
  content-services/latest/develop/reference/cmis-ref.md
Labels: PR: reviewed-approved

#308 [DOCS-6236] Securing HTML Transformations (MNT-21611)
  _data/toc/content-services.yaml
  content-services/6.2/admin/securing-html-transforms.md
  content-services/6.2/install/containers/index.md
  content-services/6.2/install/zip/index.md
  content-services/latest/admin/securing-html-transforms.md
  content-services/latest/admin/securing-install.md
  content-services/latest/install/containers/index.md
Labels: PR: unreviewed

#148 Remove white background from icons on the home page
  assets/img/ic_federation_80px.svg
  assets/img/ic_identity_80px.svg
  assets/img/ic_intelligence_80px.svg
  assets/img/ic_search_80px.svg
  assets/img/ic_sync_80px.svg
  assets/img/ic_transform_80px.svg
Labels: PR: reviewed-approved

#333 [DOCS-5987] SAML Add new way of configuring keystores
  saml-module/latest/install/index.md
Labels: PR: partially-approved, next release :arrow_right:

#334 [DOCS-6339] Update Supported Platforms page for ACS 7.0.1
  content-services/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#294 Search services 2.0.2
  _data/toc/insight-engine.yaml
  _data/toc/search-services.yaml
  content-services/6.0/support/index.md
  content-services/6.1/support/index.md
  content-services/6.2/support/index.md
  content-services/latest/install/zip/tomcat.md
  content-services/latest/support/index.md
  insight-engine/1.4/support/index.md
  insight-engine/latest/admin/index.md
  insight-engine/latest/config/indexing.md
  insight-engine/latest/config/keys.md
  insight-engine/latest/config/performance.md
  insight-engine/latest/config/security.md
  insight-engine/latest/support/index.md
  process-services/latest/support/index.md
  search-services/1.4/config/properties.md
  search-services/1.4/config/security.md
  search-services/latest/admin/index.md
  search-services/latest/config/indexing.md
  search-services/latest/config/keys.md
  search-services/latest/config/performance.md
  search-services/latest/config/properties.md
  search-services/latest/config/security.md
Labels: PR: reviewed-approved, next release :arrow_right:

#337 [DOCS-6347] Add SAP Cloud 1.1 to 7.0.1 SP page
  content-services/latest/support/index.md
Labels: PR: reviewed-approved

#341 [DOCS-6351] Add APS version workaround back in ``1.10``
  _config.yml
  _data/toc/process-services.yaml
Labels: PR: reviewed-approved

#339 [DOCS-6350] docker references update
  process-services/1.10/install/container.md
  process-services/1.11/install/container.md
  process-services/1.9/install/container.md
  process-services/latest/install/container.md
Labels: PR: reviewed-approved

#336 [DOCS-6326] - Added Java Foundation API page to 5.2
  _data/toc/content-services.yaml
  content-services/5.2/admin/audit.md
  content-services/5.2/develop/api-reference.md
  content-services/5.2/develop/apis-by-function.md
  content-services/5.2/develop/java-api-guide.md
  content-services/5.2/develop/reference/java-foundation-ref.md
  content-services/5.2/develop/repo-ext-points/content-transformers-renditions.md
  content-services/5.2/develop/rest-api-guide/index.md
  content-services/5.2/develop/software-architecture.md
Labels: PR: reviewed-approved

#342 [DOCS-6356] Add Hyland branding
  _includes/footer.html
  _includes/mainmenu.html
  _layouts/home.html
  assets/css/main.css
  assets/img/hyland-alfresco-logos-horizontal-RGB.png
  assets/js/searchbar.js
Labels: PR: reviewed-approved

#344 [DOCS-6358] fix for APS drop down issue
  _config.yml
Labels: PR: reviewed-approved

#345 Update index.md
  transformation-engine/latest/install/index.md
Labels: PR: reviewed-approved

#346 Update msi.md
  transformation-engine/latest/install/msi.md
Labels: PR: reviewed-approved
