Repository Alfresco/docs-alfresco, pull requests merged in 2021-11, with the labels that each got.

#435 [DOCS-6446] Add Example projects #435
  process-automation/images/duplicate-projects.png
  process-automation/images/example-projects.png
  process-automation/latest/model/projects.md
Labels: PR: reviewed-approved

#363 [DOCS-6397] Added API section
  process-automation/latest/develop/index.md
Labels: PR: reviewed-approved

#438 [DOCS-6472] corrected supported ACS versions
  content-services/6.1/support/index.md
  content-services/6.2/support/index.md
  content-services/7.0/support/index.md
  content-services/latest/support/index.md
  digital-workspace/1.5/support/index.md
  digital-workspace/1.6/support/index.md
  digital-workspace/2.0/support/index.md
  digital-workspace/2.1/support/index.md
  digital-workspace/2.2/support/index.md
  digital-workspace/2.3/support/index.md
  digital-workspace/latest/support/index.md
Labels: PR: reviewed-approved

#439 [DOCS-6426] Added new install path
  insight-engine/1.4/install/options.md
  insight-engine/latest/install/options.md
  insight-engine/latest/support/index.md
  search-services/1.4/install/options.md
  search-services/latest/install/options.md
  search-services/latest/support/index.md
Labels: PR: reviewed-approved

#436 [DOCS-6463] Added Document classification information
  process-automation/latest/model/connectors/aws.md
Labels: PR: reviewed-approved

#440 [DOCS-6476] Correct keys.md
  search-services/latest/config/keys.md
Labels: PR: reviewed-approved

#442 [DOCS-6477] Update Support Holiday Calendar
  support/latest/holidays.md
Labels: PR: reviewed-approved

#444 [DOCS-6481] Consistency updates for ACS docs - Using Share
  content-services/5.2/using/dashboard.md
  content-services/5.2/using/share.md
  content-services/6.0/using/share.md
  content-services/6.1/using/share.md
  content-services/6.2/using/share.md
  content-services/7.0/using/share.md
  content-services/community/using/share.md
  content-services/latest/using/share.md
Labels: PR: reviewed-approved

#446 [DOCS-6447] standarized connector event model
  process-automation/images/model-schema-editor.png
  process-automation/latest/model/connectors/index.md
  process-automation/latest/model/triggers.md
  process-automation/latest/using/index.md
Labels: PR: reviewed-approved

#448 [DOCS-6460] [MNT-21945] Add timezone configuration
  desktop-sync/latest/config/index.md
Labels: PR: partially-approved

#447 [DOCS-6461] Ansible installation update to support 7.1
  content-services/community/install/ansible.md
  content-services/latest/install/ansible.md
Labels: PR: reviewed-approved

#449 [DOCS-6487] Removed unsupported references
  search-enterprise/latest/using/unsupported.md
Labels: PR: reviewed-approved

#419 [DOCS-6257] Technical updates for SAP Connector 5.2
  sap/5.0/config/advanced.md
  sap/5.1/config/advanced.md
  sap/images/sap_inst_004_https_001.png
  sap/latest/admin/index.md
  sap/latest/admin/reference.md
  sap/latest/config/advanced.md
Labels: PR: partially-approved, next release :arrow_right:

#450 [DOCS-6474] Added new Public/Private descriptions
  process-automation/latest/model/files.md
  process-automation/latest/model/index.md
Labels: PR: reviewed-approved

#455 [DOCS-6258] Updates for SAP Connector 5.2
  sap/latest/support/index.md
Labels: PR: partially-approved

#454 [DOCS-6499] adjusted SP page from feedback
  search-enterprise/latest/support/index.md
Labels: PR: reviewed-approved

#452 [DOCS-6475] Added new parameters for the UI section
  process-automation/latest/model/interfaces.md
Labels: PR: unreviewed

#459 [DOCS-6473] Correct dependencies in ACS 7.1 docs
  content-services/latest/config/repository.md
  content-services/latest/support/index.md
Labels: PR: reviewed-approved

#458 [DOCS-6376] Update Content Services Supported Platforms pages
  content-services/6.2/support/index.md
  content-services/7.0/support/index.md
  content-services/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#460 DOCS-6493 - Adjusted the name of email connector
  process-automation/latest/model/connectors/email.md
  process-automation/latest/model/connectors/index.md
  process-automation/latest/model/processes/index.md
  process-automation/latest/model/triggers.md
Labels: PR: partially-approved

#462 [DOCS-6257] Fix link to 'Configure GenericXchange'
  sap/latest/config/advanced.md
Labels: PR: reviewed-approved, next release :arrow_right:

#451 [DOCS-6467] Alfresco Process Automation M16
  process-automation/latest/model/connectors/email.md
  process-automation/latest/model/connectors/index.md
  process-automation/latest/model/files.md
  process-automation/latest/model/forms.md
  process-automation/latest/model/index.md
  process-automation/latest/model/interfaces.md
  process-automation/latest/model/processes/index.md
  process-automation/latest/model/triggers.md
Labels: PR: reviewed-approved

#453 [DOCS-6468] DTE 2.3.1 release updates
  _data/toc/transformation-engine.yaml
  transformation-engine/2.2/admin/index.md
  transformation-engine/2.2/config/index.md
  transformation-engine/2.2/install/sdk.md
  transformation-engine/2.2/using/index.md
  transformation-engine/latest/admin/index.md
  transformation-engine/latest/config/index.md
  transformation-engine/latest/install/index.md
  transformation-engine/latest/install/msi.md
  transformation-engine/latest/install/sdk.md
  transformation-engine/latest/support/index.md
  transformation-engine/latest/using/index.md
Labels: PR: partially-approved, next release :arrow_right:

#463 [DOCS-6468] Alfresco Document Transformation Engine 2.3.1
  _data/toc/transformation-engine.yaml
  transformation-engine/2.2/admin/index.md
  transformation-engine/2.2/config/index.md
  transformation-engine/2.2/install/sdk.md
  transformation-engine/2.2/using/index.md
  transformation-engine/latest/admin/index.md
  transformation-engine/latest/config/index.md
  transformation-engine/latest/install/index.md
  transformation-engine/latest/install/msi.md
  transformation-engine/latest/install/sdk.md
  transformation-engine/latest/support/index.md
  transformation-engine/latest/using/index.md
Labels: PR: reviewed-approved

#432 Update searching.md based on part of the old documentation
  content-services/community/develop/rest-api-guide/searching.md
Labels: PR: reviewed-approved

#420 Update restapi.md
  search-services/latest/admin/restapi.md
Labels: PR: reviewed-approved, search-sie

#464 [DOCS-6378] Tweak Centera Connector support statement
  centera/latest/index.md
Labels: PR: reviewed-approved

#467 [DOCS-6504] Fix link to Configure Activities Feed
  content-services/6.0/config/subsystems.md
  content-services/6.1/config/subsystems.md
  content-services/6.2/config/subsystems.md
  content-services/7.0/config/subsystems.md
  content-services/latest/config/subsystems.md
Labels: PR: reviewed-approved

#470 DOCS-6492 Change document connector property to document service
  process-automation/latest/model/connectors/generate.md
Labels: PR: reviewed-approved

#465 DOCS-6488 - Add metadata viewer process
  process-automation/latest/model/forms.md
Labels: PR: reviewed-approved

#472 [DOCS-6377] Standardise Install integrations table
  content-services/6.0/install/zip/additions.md
  content-services/6.1/install/zip/additions.md
  content-services/6.2/install/zip/additions.md
  content-services/7.0/install/zip/additions.md
  content-services/latest/install/zip/additions.md
Labels: PR: reviewed-approved

#473 [DOCS-6505] Remove version number in APS Admin pages
  process-services/1.10/admin/index.md
  process-services/1.9/admin/index.md
Labels: PR: reviewed-approved

#479 [DOCS-6514] Fix redirects for ACS docs landing pages
  redirects/3.4/concepts/welcome-infocenter.html
  redirects/4.0/concepts/welcome-infocenter.html
  redirects/4.1/concepts/welcome-infocenter.html
  redirects/4.2/concepts/welcome-infocenter.html
  redirects/5.0/concepts/welcome.html
  redirects/5.1/concepts/welcome.html
  redirects/5.2/concepts/welcome.html
  redirects/6.0/concepts/welcome.html
  redirects/6.1/concepts/welcome.html
  redirects/6.2/concepts/master-using-intro.html
  redirects/6.2/concepts/welcome.html
Labels: PR: reviewed-approved
