Repository Alfresco/docs-alfresco, pull requests merged in 2021-09, with the labels that each got.

#362 [DOCS-6396] Align Support Handbook to Hyland
  support/latest/contact/index.md
  support/latest/packages.md
  support/latest/policies/premier.md
  support/latest/roles.md
  support/latest/severity.md
  support/latest/slt.md
Labels: PR: reviewed-approved

#355 Update Alfresco Collaboration Connector for Microsoft 365
  microsoft-365/latest/install/index.md
Labels: PR: reviewed-approved

#370 [DOCS-6403] Update Support Handbook landing page
  support/latest/index.md
Labels: PR: partially-approved

#366 [DOCS-6381] Remove highlightTexts parameter in sample config
  microsoft-outlook/2.7/config/index.md
  microsoft-outlook/latest/config/index.md
Labels: PR: partially-approved

#368 [DOCS-6395] Add wildcard capability for search configuration
  microsoft-outlook/latest/config/index.md
Labels: PR: partially-approved, next release :arrow_right:

#369 [DOCS-6401] Add prereq for using Search Services with Outlook Integration
  microsoft-outlook/latest/install/index.md
Labels: PR: partially-approved, next release :arrow_right:

#375 [DOCS-6402] Update Supported platforms page for v2.8.1
  microsoft-outlook/latest/support/index.md
Labels: PR: partially-approved

#376 SEARCH-3054 Add Alfresco Search Enterprise 3.0 to support matrix.
  content-services/latest/support/index.md
Labels: PR: partially-approved

#364 [DOCS-DOCS-6386] Rewrite review using page
  _data/toc/search-enterprise.yaml
  search-enterprise/latest/admin/index.md
  search-enterprise/latest/using/field.md
  search-enterprise/latest/using/filtering.md
  search-enterprise/latest/using/index.md
  search-enterprise/latest/using/languages.md
  search-enterprise/latest/using/unsupported.md
Labels: PR: unreviewed

#381 [DOCS-6389] Rewrite review config
  search-enterprise/latest/config/index.md
Labels: PR: unreviewed

#386 [DOCS-6405] Update ACS 7.1 upgrade pages
  content-services/community/upgrade/index.md
  content-services/images/upgrade-path-7-1.png
  content-services/latest/upgrade/index.md
Labels: PR: unreviewed

#387 [DOCS-6404] Update ACS 7.1 Install pages
  content-services/community/install/containers/docker-compose.md
  content-services/community/install/zip/additions.md
  content-services/community/install/zip/amp.md
  content-services/community/install/zip/index.md
  content-services/community/install/zip/tomcat.md
  content-services/images/compose-community.png
  content-services/images/compose-enterprise.png
  content-services/images/helm-community.png
  content-services/images/helm-eks-community.png
  content-services/images/helm-eks-enterprise.png
  content-services/images/helm-eks-s3-rds-mq-ai.png
  content-services/images/helm-eks-s3-rds-mq.png
  content-services/images/helm-enterprise.png
  content-services/latest/install/containers/customize.md
  content-services/latest/install/containers/docker-compose.md
  content-services/latest/install/containers/helm.md
  content-services/latest/install/containers/index.md
  content-services/latest/install/zip/additions.md
  content-services/latest/install/zip/amp.md
  content-services/latest/install/zip/index.md
  content-services/latest/install/zip/tomcat.md
Labels: PR: reviewed-approved

#384 [DOCS-6364] Technical updates for SAP Cloud 1.2
  _data/glossary.yaml
  _data/toc/sap-cloud.yaml
  sap-cloud/latest/config/genericxchange.md
  sap-cloud/latest/index.md
  sap-cloud/latest/install/index.md
  sap-cloud/latest/support/index.md
Labels: PR: partially-approved
