Repository Alfresco/docs-alfresco, pull requests merged in 2021-12, with the labels that each got.

#471 DOCS-6497 Add new property AllowMarkup
  process-automation/latest/model/connectors/docusign.md
Labels: PR: reviewed-approved

#477 [DOCS-6496] Update Date property
  process-automation/latest/model/processes/index.md
Labels: PR: partially-approved

#469 DOCS-6491 - Add description of new property - Content Properties to display
  process-automation/latest/model/forms.md
Labels: PR: partially-approved

#461 [DOCS-6500] Salesforce 2.3.2 version bump
  content-services/latest/support/index.md
  salesforce/latest/support/index.md
Labels: PR: partially-approved

#456 [DOCS-6469] Docker image updates for 6.2,7.0,7.1
  content-services/6.2/install/containers/customize.md
  content-services/6.2/install/containers/docker-compose.md
  content-services/6.2/install/containers/index.md
  content-services/7.0/install/containers/customize.md
  content-services/7.0/install/containers/index.md
  content-services/community/install/containers/index.md
  content-services/latest/install/containers/customize.md
  content-services/latest/install/containers/docker-compose.md
  content-services/latest/install/containers/index.md
Labels: PR: reviewed-approved

#480 [DOCS-6489] - Add customize process/task list configuration
  process-automation/images/process-list-additional-columns.png
  process-automation/images/process-list-custom-template.png
  process-automation/images/process-list-default-columns.png
  process-automation/images/process-list-new-columns.png
  process-automation/images/task-list-additional-columns.png
  process-automation/images/task-list-custom-template.png
  process-automation/images/task-list-default-columns.png
  process-automation/images/task-list-new-columns.png
  process-automation/latest/develop/index.md
Labels: PR: reviewed-approved

#481 [DOCS-6516] Update T-Engine version for DTE 2.3.1
  transformation-engine/latest/install/msi.md
  transformation-engine/latest/support/index.md
Labels: PR: partially-approved

#484 DOCS-6484 - Add Deactivate user task re-assignment description
  process-services/latest/using/process/bpmn.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#483 [DOCS-6517] -Remove pending jobs note from upgrade page
  process-services/latest/upgrade/index.md
Labels: PR: partially-approved, DO NOT MERGE 🙅🏻‍♂️

#482 DOCS-6485 - Add conditional relationship to two dropdown lists
  process-automation/latest/model/forms.md
Labels: PR: reviewed-approved
