Repository Alfresco/docs-alfresco, pull requests merged in 2021-10, with the labels that each got.

#385 [DOCS-6418] ATS 1.4.1 version bump
  content-services/latest/install/ansible.md
  content-services/latest/install/containers/docker-compose.md
  content-services/latest/install/containers/helm.md
  content-services/latest/install/containers/index.md
  content-services/latest/install/zip/index.md
  transform-service/latest/install/index.md
  transform-service/latest/support/index.md
Labels: PR: reviewed-approved

#383 [DOCS-6360] MS 365 1.1.1 version bump
  microsoft-365/latest/install/index.md
  microsoft-365/latest/support/index.md
Labels: PR: reviewed-approved

#382 [DOCS-6417] Extension Inspector 1.2 version bump
  content-services/latest/develop/extension-inspector.md
Labels: PR: reviewed-approved

#390 [DOCS-6413] Add compatible releases for ACS 7.1
  content-services/6.2/support/index.md
  content-services/7.0/support/index.md
  content-services/latest/support/index.md
Labels: PR: reviewed-approved

#392 [DOCS-6276] Event Gateway & SDK 5.1
  _data/toc/content-services.yaml
  content-services/images/event_gateway_big_picture.png
  content-services/images/sdk52_big_picture.png
  content-services/latest/develop/oop-ext-points/event-gateway.md
  content-services/latest/develop/oop-sdk.md
Labels: PR: reviewed-approved

#380 [DOCS-6332] Alfresco Collaboration Connector for Teams 1.0
  _config.yml
  _data/home.yaml
  _data/scopes.yaml
  _data/toc/microsoft-teams.yaml
  microsoft-teams/images/adw-login-page.png
  microsoft-teams/images/adw-login-successful.png
  microsoft-teams/images/azure-bot-configuration-oauth.png
  microsoft-teams/images/azure-bot-configuration.png
  microsoft-teams/images/azure-bot-create-checks-passed.png
  microsoft-teams/images/azure-bot-create.png
  microsoft-teams/images/azure-bot-deployment-complete.png
  microsoft-teams/images/azure-bot-oauth-config-test-connection.png
  microsoft-teams/images/azure-portal-home-page.png
  microsoft-teams/images/collaboration-connector-teams-overview.png
  microsoft-teams/images/ms-teams-apps.png
  microsoft-teams/images/ms-teams-integ-app-bottom-toolbar.png
  microsoft-teams/images/ms-teams-integ-app-doc-view-adw.png
  microsoft-teams/images/ms-teams-integ-app-in-msg-extensions.png
  microsoft-teams/images/ms-teams-integ-app-loading.png
  microsoft-teams/images/ms-teams-integ-app-popup-menu.png
  microsoft-teams/images/ms-teams-integ-app-search-dialog-result-item-share.png
  microsoft-teams/images/ms-teams-integ-app-search-dialog-result-item-shared.png
  microsoft-teams/images/ms-teams-integ-app-search-dialog-result-item.png
  microsoft-teams/images/ms-teams-integ-app-search-dialog-result.png
  microsoft-teams/images/ms-teams-integ-app-search-dialog.png
  microsoft-teams/images/ms-teams-integ-app-signin-dialog.png
  microsoft-teams/images/ms-teams-integ-app-signin-link.png
  microsoft-teams/latest/index.md
  microsoft-teams/latest/install/index.md
  microsoft-teams/latest/support/index.md
  microsoft-teams/latest/using/index.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#347 [DOCS-6353] Search Enterprise 3.0
  _config.yml
  _data/home.yaml
  _data/toc/search-enterprise.yaml
  content-services/latest/support/index.md
  search-enterprise/images/alfresco_repo_web_console.png
  search-enterprise/images/elasticsearch-upgrading-1.png
  search-enterprise/images/elasticsearch-upgrading-2.png
  search-enterprise/images/elasticsearch_connector_architecture.png
  search-enterprise/images/elasticsearch_flows.png
  search-enterprise/latest/admin/index.md
  search-enterprise/latest/config/index.md
  search-enterprise/latest/index.md
  search-enterprise/latest/install/index.md
  search-enterprise/latest/support/index.md
  search-enterprise/latest/upgrade/index.md
  search-enterprise/latest/using/field.md
  search-enterprise/latest/using/filtering.md
  search-enterprise/latest/using/index.md
  search-enterprise/latest/using/languages.md
  search-enterprise/latest/using/unsupported.md
Labels: PR: reviewed-approved, next release :arrow_right:, search-sie, DO NOT MERGE 🙅🏻‍♂️

#373 [DOCS-6361] Add Alfresco Outlook Integration 2.8.1 docs
  microsoft-outlook/2.7/config/index.md
  microsoft-outlook/latest/config/index.md
  microsoft-outlook/latest/install/index.md
  microsoft-outlook/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#393 [DOCS-6421] SDK 4.3 updates
  _data/toc/content-services.yaml
  content-services/latest/develop/sdk.md
Labels: PR: reviewed-approved

#379 [DOCS-6284] edits final m13 changes
  _data/toc/process-automation.yaml
  process-automation/images/auto-completion.png
  process-automation/images/condition-builder.png
  process-automation/images/event.png
  process-automation/images/expression-editor.png
  process-automation/images/hints.png
  process-automation/images/statement-editor.png
  process-automation/latest/develop/index.md
  process-automation/latest/model/connectors/aws.md
  process-automation/latest/model/connectors/docusign.md
  process-automation/latest/model/connectors/outlook.md
  process-automation/latest/model/connectors/teams.md
  process-automation/latest/model/projects.md
  process-automation/latest/using/index.md
Labels: PR: partially-approved

#394 [DOCS-6410] Update how to access Downloads in Support Portal/Hyland Community
  content-services/latest/admin/import-transfer.md
  content-services/latest/config/action.md
  content-services/latest/develop/sdk.md
  content-services/latest/install/zip/index.md
  content-services/latest/install/zip/tomcat.md
Labels: PR: unreviewed

#396 [DOCS-6414] Updates for Content Connector for Salesforce 2.3.1
  salesforce/latest/install/index.md
  salesforce/latest/support/index.md
Labels: PR: reviewed-approved

#391 [DOCS-6349] ACS 7.1 Stack updates
  content-services/latest/support/index.md
Labels: PR: unreviewed

#397 [DOCS-6372] AGS Community
  governance-services/community/develop/index.md
  governance-services/community/install/docker.md
  governance-services/community/install/zip.md
  governance-services/community/support/index.md
  governance-services/latest/develop/index.md
  governance-services/latest/install/zip.md
Labels: PR: reviewed-approved, next release :arrow_right:

#400 Minor fix to ACS landing page
  content-services/latest/index.md
Labels: PR: reviewed-approved

#404 [DOCS-6433] Clarify Outlook T-Engine version to use for v2.8.1
  microsoft-outlook/latest/install/index.md
  microsoft-outlook/latest/support/index.md
Labels: PR: reviewed-approved

#403 [DOCS-6432] Update Support Handbook - Premier Services
  _data/toc/support.yaml
  support/latest/packages.md
  support/latest/policies/premier.md
  support/latest/premier.md
  support/latest/roles.md
  support/latest/slt.md
Labels: PR: reviewed-approved

#406 Update index.md
  governance-services/latest/upgrade/index.md
Labels: PR: reviewed-approved

#409 [DOCS-6427] SDK 4.3 Community update
  _data/toc/content-services.yaml
  content-services/community/develop/sdk.md
  content-services/latest/develop/sdk.md
Labels: PR: reviewed-approved

#422 [DOCS-6438] - Facebook 1.0 docs
  facebook/latest/install/index.md
  facebook/latest/support/index.md
Labels: PR: unreviewed
