Repository Alfresco/docs-alfresco, pull requests merged in 2022-10, with the labels that each got.

#799 [DOCS-6951] Add corrections to monitor.md
  process-automation/latest/admin/monitor.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#800 [DOCS-6920] Update ACS Supported Platforms pages
  content-services/7.0/support/index.md
  content-services/7.1/support/index.md
  content-services/latest/support/index.md
Labels: PR: reviewed-approved

#804 [DOCS-6922] Add image and numbered list
  content-services/images/modheader.png
  content-services/latest/install/containers/docker-compose.md
Labels: PR: reviewed-approved

#812 [DOCS-6900] Add new parameter Set dynamic date range
  process-automation/latest/model/forms.md
Labels: PR: partially-approved

#813 [DOCS-6901] Add Clickable hyperlink
  digital-workspace/latest/process/starting.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#815 [DOCS-6954] Add missing redirects for Search Services docs
  redirects/6.2/concepts/intrans-metadata-conf-patch.html
  redirects/6.2/concepts/intrans-metadata-feature.html
  redirects/6.2/concepts/solr-overview.html
  redirects/6.2/concepts/solr-shard-overview.html
Labels: PR: reviewed-approved

#807 [DOCS-6888] Add print option
  digital-workspace/images/print.png
  digital-workspace/latest/process/tasks.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#817 [DOCS-6895] Add sequential information
  process-automation/latest/model/processes/bpmn.md
Labels: PR: partially-approved

#811 [DOCS-6965] - Add Star icon information
  process-automation/latest/model/projects.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#805 [DOCS-6889] Add recently used sentence
  digital-workspace/latest/process/starting.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#803 [DOCS-6956] Supported platforms updates
  insight-engine/latest/support/index.md
  search-services/latest/support/index.md
Labels: PR: reviewed-approved

#810 [DOCS-6906] Add collaborators column
  process-automation/latest/model/projects.md
Labels: PR: reviewed-changes-requested, DO NOT MERGE 🙅🏻‍♂️

#834 [DOCS-6984] Update Support Handbook - Support Case Life Cycle page
  support/latest/contact/case-lifecycle.md
Labels: PR: reviewed-approved

#841 [DOCS-6988] Update Case Status Definitions in Support Handbook
  support/latest/index.md
  support/latest/resources/issue-status.md
Labels: PR: reviewed-approved

#830 [DOCS-6905] Add Application Service Credentials info
  process-automation/latest/model/authentication.md
Labels: PR: reviewed-approved

#839 [DOCS-6945] Clarify Elasticsearch version
  search-enterprise/latest/config/index.md
  search-enterprise/latest/index.md
  search-enterprise/latest/install/index.md
  search-enterprise/latest/support/index.md
  search-enterprise/latest/upgrade/index.md
Labels: PR: partially-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#724 [DOCS-6813] Support for Opensearch
  search-enterprise/latest/config/index.md
  search-enterprise/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#842 Revert "[DOCS-6813] Support for Opensearch"
  search-enterprise/latest/config/index.md
  search-enterprise/latest/support/index.md
Labels: PR: unreviewed
