Repository Alfresco/docs-alfresco, pull requests merged in 2022-02, with the labels that each got.

#505 Ats 1.5 alan1
  transform-service/latest/index.md
Labels: PR: unreviewed

#506 ATS 1.5 / ACS 7.1.1 (alan2)
  transform-service/latest/index.md
Labels: PR: reviewed-approved

#508 [DOCS-6512] Desktop Sync 1.8 release updates
  desktop-sync/latest/config/index.md
  desktop-sync/latest/index.md
  desktop-sync/latest/install/index.md
  desktop-sync/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#512 [DOCS-6519] Adding ATS 1.5 and ImageMagick v7.1.0 to the 7.1.1 support page
  content-services/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#511 [DOCS-6532] Adding deleteRendition and deleteVersionRendition ReST API endpoints
  content-services/latest/develop/rest-api-guide/folders-files.md
Labels: PR: reviewed-approved, next release :arrow_right:

#513 [DOCS-6527] Add Sync Service 3.5 and Desktop Sync 1.8 for ACS 7.1.1 release
  content-services/latest/support/index.md
Labels: PR: unreviewed, next release :arrow_right:

#514 [DOCS-6543] Update Docker Compose steps
  content-services/latest/install/containers/docker-compose.md
Labels: PR: reviewed-approved, next release :arrow_right:

#515 [DOCS-6527] Update Desktop Sync support in previous ACS versions
  content-services/5.2/support/index.md
  content-services/6.0/support/index.md
  content-services/6.1/support/index.md
  content-services/6.2/support/index.md
  content-services/7.0/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#496 [DOCS-6537] - Alfresco Governance Services 7.1.1
  governance-services/latest/config/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#487 SFDCENG-925 : Community VF Configuration and Setup
  salesforce/latest/using/community.md
Labels: PR: partially-approved, next release :arrow_right:

#518 [DOCS-6561] - Correct Supported Platforms
  process-services/2.0/support/index.md
  process-services/2.1/support/index.md
  process-services/latest/support/index.md
Labels: PR: reviewed-approved

#517 [DOCS-6552] - Update process workflow
  process-automation/latest/using/index.md
Labels: PR: partially-approved

#516 [DOCS-6551] - Add new field
  process-automation/latest/model/processes/index.md
Labels: PR: partially-approved

#521 [DOCS-6574] - Remove incorrect note and add new one
  process-automation/latest/model/forms.md
Labels: PR: partially-approved

#524 [DOCS-6568] - Change Content connector
  process-automation/latest/model/connectors/content.md
Labels: PR: reviewed-approved

#522 [DOCS-6569] - Add Binding providers
  process-automation/latest/model/scripts.md
Labels: PR: reviewed-approved

#525 [DOCS-6571] - Add new check box
  process-automation/latest/model/forms.md
Labels: PR: reviewed-approved

#528 [DOCS-6566] - Add logs
  process-automation/latest/admin/release.md
Labels: PR: reviewed-approved

#529 [DOCS-6564] Add monitoring dashboard
  process-automation/latest/admin/release.md
Labels: PR: reviewed-approved

#530 [DOCS-6595] Fix tooltip in AGS docs (remove "" in glossary)
  _data/glossary.yaml
Labels: PR: reviewed-approved

#504 [DOCS-6553] Fix heading levels
  search-services/latest/admin/index.md
Labels: PR: reviewed-approved, search-sie
