Repository Alfresco/docs-alfresco, pull requests merged in 2022-11, with the labels that each got.

#827 [DOCS-6932] [DOCS-6972] Add Sync Service 3.8 compatibility with ACS
  content-services/7.2/support/index.md
  content-services/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#846 [DOCS-6989] Add search scope for Support Handbook
  _data/scopes.yaml
Labels: PR: reviewed-approved

#847 [DOCS-6928] Extension Inspector 1.5 version bump
  content-services/latest/develop/extension-inspector.md
Labels: PR: partially-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#801 [DOCS-6917] Added new prop ldap.authentication.initial.checks.enabled
  content-services/latest/admin/auth-sync.md
Labels: PR: reviewed-approved, next release :arrow_right:

#852 delete a duplicate word
  process-services/latest/using/share-connector.md
Labels: PR: reviewed-approved

#856 [DOCS-6998] Update Salesforce Connector compatibility with ACS 7.3
  content-services/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#802 [DOCS-6866] Security related updates for View in Browser function
  content-services/7.0/config/repository.md
  content-services/7.0/using/content/manage.md
  content-services/7.1/config/repository.md
  content-services/7.1/using/content/manage.md
  content-services/7.2/config/repository.md
  content-services/7.2/using/content/manage.md
  content-services/latest/config/repository.md
  content-services/latest/using/content/manage.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#833 [DOCS-6985] Update SAP Applications 5.2.1 compatibility in Content Services docs
  content-services/latest/support/index.md
Labels: PR: unreviewed, next release :arrow_right:

#836 [DOCS-6973] Update compatible ACS versions for Desktop Sync 1.13.1
  desktop-sync/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#835 [DOCS-6974] Update Desktop Sync 1.13.1 compatibility with ACS
  content-services/7.0/support/index.md
  content-services/7.1/support/index.md
  content-services/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#826 [DOCS-6932] Alfresco Sync Service 3.8 release updates
  sync-service/3.0/support/index.md
  sync-service/3.1/support/index.md
  sync-service/3.2/support/index.md
  sync-service/3.3/support/index.md
  sync-service/3.4/support/index.md
  sync-service/3.5/support/index.md
  sync-service/3.6/support/index.md
  sync-service/3.7/support/index.md
  sync-service/latest/config/index.md
  sync-service/latest/index.md
  sync-service/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#816 [MNT-22629] New "allow.unsecure.callback.jsonp" repo property
  content-services/7.1/develop/rest-api-guide/index.md
  content-services/7.2/develop/rest-api-guide/index.md
  content-services/latest/develop/rest-api-guide/index.md
Labels: PR: reviewed-approved

#858 [DOCS-7010] Update supported platforms
  content-services/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#861 [DOCS-6943] Update supported ACS SDK versions to 4.5 and 5.2
  _data/toc/content-services.yaml
  content-services/latest/develop/oop-sdk.md
  content-services/latest/develop/sdk.md
Labels: PR: unreviewed, next release :arrow_right:

#864 [DOCS-7013] Fix site config for latest DTE 2.3 docs
  _config.yml
Labels: PR: reviewed-approved

#850 [DOCS-6999] Update Supported Platforms page (Google Docs Integration 3.3)
  content-services/7.2/support/index.md
  content-services/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#855 [DOCS-6996] Update compatible ACS version for Salesforce Connector 2.3.x
  salesforce/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#862 [DOCS-6967] Content Services 7.3 Upgrade updates
  content-services/images/upgrade-path-7.3.png
  content-services/latest/upgrade/index.md
Labels: PR: reviewed-approved

#828 [DOCS-6627] Admin node cleanup instruction added to 7.2 and 7.3
  _data/toc/content-services.yaml
  content-services/7.2/admin/node-cleanup.md
  content-services/latest/admin/node-cleanup.md
Labels: PR: reviewed-approved, next release :arrow_right:

#872 [DOCS-6056] Update permissions for MNT-21638
  content-services/latest/develop/repo-ext-points/permissions.md
Labels: PR: reviewed-approved, next release :arrow_right:

#857 [DOCS-6970] ACS 7.3 Community Updates
  content-services/community/config/activemq.md
  content-services/community/config/repository.md
  content-services/community/install/zip/amp.md
  content-services/community/install/zip/index.md
  content-services/community/install/zip/tomcat.md
Labels: PR: reviewed-approved, next release :arrow_right:

#851 [DOCS-6969] What's New update for ACS 7.3
  content-services/latest/release/index.md
Labels: PR: unreviewed, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#843 [DOCS-6813] Add support for Opensearch
  search-enterprise/latest/config/index.md
  search-enterprise/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#860 [DOCS-7006] Alfresco Governance Services 7.3 Community Edition
  governance-services/community/develop/index.md
  governance-services/community/install/docker.md
  governance-services/community/install/zip.md
Labels: PR: reviewed-approved, next release :arrow_right:

#822 [DOCS-6747] ACS Helm install updates based on PR #356, #357, #358
  content-services/6.2/install/containers/helm.md
  content-services/7.0/install/containers/helm.md
  content-services/7.1/install/containers/helm.md
  content-services/7.2/install/containers/helm.md
  content-services/latest/install/containers/helm.md
Labels: PR: partially-approved

#875 [DOCS-7015] Add properties to control JavaScript execution
  content-services/6.2/config/repository.md
  content-services/7.0/config/repository.md
  content-services/7.1/config/repository.md
  content-services/7.2/config/repository.md
  content-services/latest/config/repository.md
Labels: PR: unreviewed, next release :arrow_right:

#876 [DOCS-6958] Update AOS configuration required to integrate with Identity Service
  microsoft-office/latest/config/index.md
Labels: PR: partially-approved, next release :arrow_right:

#849 [DOCS-6966] Updates to ACS 7.3 Install section
  content-services/latest/install/containers/customize.md
  content-services/latest/install/containers/docker-compose.md
  content-services/latest/install/zip/additions.md
  content-services/latest/install/zip/amp.md
  content-services/latest/install/zip/index.md
  content-services/latest/install/zip/tomcat.md
Labels: PR: reviewed-approved, next release :arrow_right:

#808 [DOCS-6944] Update Content Services Supported Platforms pages (ACS 7.3)
  content-services/7.0/support/index.md
  content-services/7.1/support/index.md
  content-services/7.2/support/index.md
  content-services/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#878 [DOCS-6483] Add new upgrade for legacy ACS versions
  search-enterprise/images/close-elasticsearch-gap.png
  search-enterprise/images/elastic-index.png
  search-enterprise/images/end-user-perspective.png
  search-enterprise/images/final-state.png
  search-enterprise/images/populate-index.png
  search-enterprise/images/shutdown-mirrored-two.png
  search-enterprise/images/start-elasticsearch.png
  search-enterprise/images/start-mirrored.png
  search-enterprise/images/upgrading-initial-enviro.png
  search-enterprise/latest/upgrade/index.md
Labels: PR: unreviewed, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#848 [DOCS-6992] Updated Content Application versions
  digital-workspace/2.9/develop/deploy.md
  digital-workspace/2.9/develop/manage.md
  digital-workspace/3.0/develop/deploy.md
  digital-workspace/3.0/develop/manage.md
  digital-workspace/latest/develop/deploy.md
  digital-workspace/latest/develop/manage.md
Labels: PR: partially-approved, next release :arrow_right:

#880 [DOCS-6923] Remove unsupported references
  search-enterprise/latest/using/languages.md
  search-enterprise/latest/using/unsupported.md
Labels: PR: reviewed-approved

#869 [DOCS-6931] Mobile Workspace 1.5
  mobile-workspace/images/add-attachment.png
  mobile-workspace/images/date-change.png
  mobile-workspace/images/mark-complete.png
  mobile-workspace/latest/using/index.md
Labels: PR: partially-approved, next release :arrow_right:

#883 [DOCS-7005] Content Services 7.3 Community docker image updates
  content-services/community/install/containers/docker-compose.md
Labels: PR: reviewed-approved, next release :arrow_right:

#879 [DOCS-6501] Add CMIS support
  search-enterprise/latest/index.md
  search-enterprise/latest/support/index.md
  search-enterprise/latest/using/field.md
  search-enterprise/latest/using/index.md
  search-enterprise/latest/using/languages.md
  search-enterprise/latest/using/unsupported.md
Labels: PR: partially-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#844 [DOCS-6955] User profile editing
  digital-workspace/latest/troubleshooting/index.md
Labels: PR: partially-approved, next release :arrow_right:

#887 [DOCS-6557] Remove docs for Alfresco Content Services for Mobile
  _config.yml
  _data/home.yaml
  _data/scopes.yaml
  _data/toc/content-mobile.yaml
  _layouts/docs.html
  assets/img/logo_cm_72px.svg
  content-mobile/images/android-options-icon.png
  content-mobile/images/android-plus-icon.png
  content-mobile/images/android-restricted-icon.png
  content-mobile/images/android-x-icon.png
  content-mobile/images/ios-comment-icon.png
  content-mobile/images/ios-history-icon.png
  content-mobile/images/ios-map-icon.png
  content-mobile/images/ios-plus-icon.png
  content-mobile/images/ios-preview-icon.png
  content-mobile/images/ios-properties-icon.png
  content-mobile/images/ios-selected-icon.png
  content-mobile/latest/config/index.md
  content-mobile/latest/index.md
  content-mobile/latest/using/index.md
  content-services/6.0/config/mobile.md
  content-services/6.1/config/mobile.md
  content-services/6.2/config/mobile.md
  content-services/7.0/config/mobile.md
  content-services/7.1/config/mobile.md
  content-services/7.2/config/mobile.md
  content-services/community/config/mobile.md
  content-services/latest/config/mobile.md
Labels: PR: partially-approved
