Repository Alfresco/docs-alfresco, pull requests merged in 2022-08, with the labels that each got.

#744 [DOCS-6752] Alfresco Outlook Integration 2.9.1
  microsoft-outlook/latest/config/index.md
  microsoft-outlook/latest/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#734 [DOCS-6835] Add .x and some other minor corrections
  insight-engine/latest/config/indexing.md
  insight-engine/latest/config/performance.md
  insight-engine/latest/install/options.md
  insight-engine/latest/using/index.md
  search-services/latest/config/indexing.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#756 [DOCS-6848] Minor fixes to Enterprise Docker Compose page
  content-services/latest/install/containers/docker-compose.md
Labels: PR: unreviewed, next release :arrow_right:

#729 [DOCS-6803] [DOCS-6847] Alfresco Content Services 7.2.1
  content-services/7.0/support/index.md
  content-services/7.1/support/index.md
  content-services/latest/install/containers/docker-compose.md
  content-services/latest/support/index.md
  google-drive/latest/support/index.md
  microsoft-365/latest/support/index.md
  saml-module/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#708 [DOCS-6126] Digital Workspace developer documentation
  _data/toc/digital-workspace.yaml
  content-services/7.0/develop/software-architecture.md
  content-services/7.1/develop/software-architecture.md
  content-services/latest/develop/software-architecture.md
  digital-workspace/images/adw-extension-new-button.png
  digital-workspace/images/adw-extension-new-library.png
  digital-workspace/images/develop-arch.png
  digital-workspace/images/develop-front-end.png
  digital-workspace/latest/develop/deploy.md
  digital-workspace/latest/develop/extensions.md
  digital-workspace/latest/develop/index.md
  digital-workspace/latest/develop/manage.md
  digital-workspace/latest/extensions/index.md
  digital-workspace/latest/media/index.md
  redirects/adw/concepts/developing-extensions.html
  redirects/adw1.0/concepts/developing-extensions.html
  redirects/adw1.1/concepts/developing-extensions.html
  redirects/adw1.2/concepts/developing-extensions.html
  redirects/adw1.3/concepts/developing-extensions.html
  redirects/adw1.4/concepts/developing-extensions.html
Labels: PR: partially-approved

#758 [DOCS-6673] Add Alfresco Extension Inspector 1.4
  content-services/latest/develop/extension-inspector.md
Labels: PR: reviewed-approved, next release :arrow_right:

#755 [DOCS-6823] Update New Folder, Move, Rename, Scan
  mobile-workspace/latest/using/index.md
Labels: documentation, PR: unreviewed, PR: reviewed-changes-requested, PR: partially-approved, DO NOT MERGE 🙅🏻‍♂️

#751 [DOCS-6858] Update Transform Engine notes with additional clarification
  transform-service/1.2/install/index.md
  transform-service/1.3/install/index.md
  transform-service/1.4/install/index.md
  transform-service/latest/install/index.md
Labels: PR: reviewed-approved, tracked

#745 [DOCS-6846] Update notes for enterprise users who install ACS with zip
  content-services/7.0/install/zip/index.md
  content-services/7.1/install/zip/index.md
  content-services/community/install/zip/index.md
  content-services/latest/install/zip/index.md
Labels: PR: reviewed-approved, tracked

#760 [DOCS-6846][DOCS-6858] Fix broken link and minor corrections
  content-services/7.0/install/zip/index.md
  content-services/7.1/install/zip/index.md
  content-services/community/install/zip/index.md
  content-services/latest/install/zip/index.md
  transform-service/1.2/install/index.md
  transform-service/1.3/install/index.md
  transform-service/1.4/install/index.md
  transform-service/latest/install/index.md
Labels: PR: partially-approved

#759 DOCS-6863 Add unsupported features section for Search Services 2.x
  _data/toc/search-services.yaml
  search-services/latest/upgrade/breaking-changes-1.x.md
Labels: PR: reviewed-approved, search-sie

#763 [DOCS-6872] Add Content Services 7.2.x as compatible version for SAP products
  sap-cloud/latest/support/index.md
  sap/latest/support/index.md
Labels: PR: partially-approved
