Repository Alfresco/docs-alfresco, pull requests merged in 2022-07, with the labels that each got.

#705 [DOCS-6764] Adding the scheduler contract path property to SFS startup cmd line
  transform-service/latest/install/index.md
Labels: PR: reviewed-approved

#703 [DOCS-6033] Fix configuration guidance for APS Action AMP
  content-services/6.2/config/action.md
  content-services/7.0/config/action.md
  content-services/7.1/config/action.md
  content-services/latest/config/action.md
Labels: PR: reviewed-approved

#709 [DOCS-6765] Fix TOC in ACS Community docs - Tutorials section
  _data/toc/content-services-tutorial.yaml
  content-services/community/tutorial/index.md
Labels: PR: reviewed-approved

#701 [MNT-22325] Copy Keystore to installation info for 7.x
  content-services/7.0/install/zip/tomcat.md
  content-services/7.1/install/zip/tomcat.md
  content-services/latest/install/zip/tomcat.md
Labels: PR: reviewed-approved

#685 [DOCS-6715] Update Teams integration installation instructions so we recommend app being installed by admin
  microsoft-teams/images/ms-teams-admin-center-manage-apps.png
  microsoft-teams/images/ms-teams-admin-center-upload-app.png
  microsoft-teams/images/ms-teams-apps.png
  microsoft-teams/images/ms-teams-manage-your-apps.png
  microsoft-teams/images/ms-teams-publish-app-form.png
  microsoft-teams/latest/install/index.md
Labels: PR: partially-approved

#712 [DOCS-6394] ATS host URL change in command line start
  transform-service/1.2/install/index.md
  transform-service/1.3/install/index.md
  transform-service/1.4/install/index.md
  transform-service/latest/install/index.md
Labels: PR: reviewed-approved

#710 [DOCS-6792] Fix get audit app ReST URL for all versions
  content-services/5.2/develop/rest-api-guide/audit-apps.md
  content-services/6.0/develop/rest-api-guide/audit-apps.md
  content-services/6.1/develop/rest-api-guide/audit-apps.md
  content-services/6.2/develop/rest-api-guide/audit-apps.md
  content-services/7.0/develop/rest-api-guide/audit-apps.md
  content-services/7.1/develop/rest-api-guide/audit-apps.md
  content-services/latest/develop/rest-api-guide/audit-apps.md
Labels: PR: reviewed-approved

#718 [DOCS-6540] Fix table for bulk import fields and values
  content-services/5.2/admin/import-transfer.md
  content-services/6.0/admin/import-transfer.md
  content-services/6.1/admin/import-transfer.md
  content-services/6.2/admin/import-transfer.md
  content-services/7.0/admin/import-transfer.md
  content-services/7.1/admin/import-transfer.md
  content-services/community/admin/import-transfer.md
  content-services/latest/admin/import-transfer.md
Labels: PR: reviewed-approved

#719 [DOCS-6603] Fix code block in Process Services upgrade page
  process-services/2.0/upgrade/index.md
  process-services/2.1/upgrade/index.md
  process-services/2.2/upgrade/index.md
  process-services/latest/upgrade/index.md
Labels: PR: reviewed-approved

#720 [DOCS-6609] Fix text formatting in Content Services - Configure file servers page
  content-services/5.2/config/file-servers.md
  content-services/6.0/config/file-servers.md
  content-services/6.1/config/file-servers.md
  content-services/6.2/config/file-servers.md
  content-services/7.0/config/file-servers.md
  content-services/7.1/config/file-servers.md
  content-services/community/config/file-servers.md
  content-services/latest/config/file-servers.md
Labels: PR: reviewed-approved

#721 [DOCS-6619] Fix typos in Content Services docs
  content-services/5.2/admin/security.md
  content-services/5.2/admin/workflows.md
  content-services/6.0/admin/security.md
  content-services/6.1/admin/security.md
  content-services/6.2/admin/security.md
  content-services/6.2/admin/workflows.md
  content-services/7.0/admin/security.md
  content-services/7.0/install/zip/additions.md
  content-services/7.1/admin/security.md
  content-services/7.1/develop/rest-api-guide/folders-files.md
  content-services/7.1/install/zip/additions.md
  content-services/community/admin/security.md
  content-services/community/admin/workflows.md
  content-services/community/install/zip/additions.md
  content-services/latest/admin/security.md
  content-services/latest/develop/rest-api-guide/folders-files.md
  content-services/latest/install/zip/additions.md
Labels: PR: reviewed-approved

#664 [DOCS-6768] Fix missing operator '|' and add missing character escaping for CMIS query examples
  search-services/latest/using/index.md
Labels: PR: reviewed-approved, tracked

#723 [DOCS-6768] Fix missing characters for CMIS query examples
  insight-engine/1.0/using/sql/syntax.md
  insight-engine/1.1/using/sql/syntax.md
  insight-engine/1.4/using/sql/syntax.md
  insight-engine/latest/using/sql/syntax.md
  search-services/1.3/using/index.md
  search-services/1.4/using/index.md
Labels: PR: partially-approved

#722 [DOCS-6722] Add Docker Desktop Resources screenshot and guidance
  content-services/images/docker-desktop-resources.png
  content-services/latest/install/containers/docker-compose.md
Labels: PR: unreviewed

#726 [DOCS-6782] Add new version upload option
  process-automation/latest/model/forms.md
Labels: PR: reviewed-approved

#717 DOCS-6781 Add size of preview information
  process-automation/images/form-size.png
  process-automation/latest/model/forms.md
Labels: PR: reviewed-approved

#725 [DOCS-6779] Remove keycloak references
  process-automation/images/authentication.png
  process-automation/latest/model/authentication.md
Labels: PR: reviewed-approved

#713 DOCS-6776 - Add variable text and image
  process-automation/images/process-variable-digital.png
  process-automation/latest/model/processes/index.md
Labels: PR: reviewed-approved

#700 [DOCS- 6775] Add new column functionality
  process-automation/images/move-column.png
  process-automation/images/select-columns.png
  process-automation/latest/using/index.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#731 [DOCS-6798] Add Alfresco Desktop Sync 1.12 compatibility to ACS docs
  content-services/7.0/support/index.md
  content-services/7.1/support/index.md
  content-services/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#736 [DOCS-6844] Provide the exact link for Google Docs Integration package download
  google-drive/latest/install/index.md
Labels: PR: reviewed-approved

#716 [DOCS-6806] Update release summary for Desktop Sync 1.12 and 1.11
  desktop-sync/1.11/index.md
  desktop-sync/images/initialsync-1.12.png
  desktop-sync/images/initialsync-mac-1.12.png
  desktop-sync/images/setup-mac-1.9.png
  desktop-sync/latest/index.md
  desktop-sync/latest/using/select-to-sync.md
Labels: PR: partially-approved, next release :arrow_right:

#737 [DOCS-6841] Add new Content Services 7.2 redirects
  redirects/7.2/concepts/intrans-metadata-conf-patch.html
  redirects/7.2/concepts/intrans-metadata-feature.html
Labels: PR: reviewed-approved

#743 [DOCS-6808] Add dependent picklist feature in Outlook Integration
  microsoft-outlook/latest/config/index.md
  microsoft-outlook/latest/index.md
Labels: PR: partially-approved

#728 [DOCS-6786] Add clarification info about SS and SIE
  insight-engine/latest/index.md
  search-services/latest/index.md
Labels: PR: partially-approved

#699 [DOCS-6770] Add variable information
  process-automation/latest/model/connectors/aws.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#727 [DOCS-6778] Add info for Set left label for fields
  process-automation/latest/model/forms.md
Labels: PR: reviewed-approved

#730 [DOCS-6780] Add Static Value information
  process-automation/latest/model/processes/bpmn.md
Labels: PR: reviewed-approved

#715 DOCS-6811 Add Replay service task
  process-automation/latest/develop/index.md
Labels: PR: partially-approved

#747 [DOCS-6750] Update ACS Community Edition Docker Compose steps to include the Content App
  content-services/community/install/containers/docker-compose.md
  content-services/images/compose-community.png
Labels: PR: reviewed-approved

#748 [DOCS-6812] Update MySQL database and driver versions for ACS 7.2.1
  content-services/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#752 Add Alfresco Collaboration Connector for Teams 1.1 compatibility
  content-services/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#732 [DOCS-6807] Add Process Analytics
  process-automation/images/process-analytics.png
  process-automation/latest/using/index.md
Labels: PR: reviewed-approved

#741 [DOCS-6830] SAML Module 1.2.3 added
  content-services/latest/support/index.md
  saml-module/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#746 [DOCS-6831] GoogleDocs Integration 3.2.2
  content-services/7.1/support/index.md
  content-services/latest/support/index.md
  google-drive/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#753 [DOCS-6852] Add RHEL 8.5 to supported stack for ACS 7.2.1
  content-services/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#742 [DOCS-6827] Connector for Microsoft 365 1.1.3 new version
  content-services/latest/support/index.md
  microsoft-365/latest/support/index.md
Labels: PR: unreviewed, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️
