Repository Alfresco/docs-alfresco, pull requests merged in 2022-03, with the labels that each got.

#551 [DOCS-6594] Fix notes
  microsoft-outlook/2.8/using/index.md
  microsoft-outlook/latest/using/index.md
Labels: PR: unreviewed

#548 [DOCS-6620] Remove references to source code access in DTE docs
  content-services/5.2/install/index.md
  transformation-engine/2.2/install/sdk.md
Labels: PR: reviewed-approved

#553 [DOCS-6618] Remove unsupported components from Outlook 2.9
  microsoft-outlook/latest/install/index.md
  microsoft-outlook/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#546 [DOCS-6606] Update Supported platforms and versions
  sync-service/latest/config/index.md
  sync-service/latest/support/index.md
  sync-service/latest/upgrade/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#558 [DOCS-6592] Add min and max values for configuration options
  desktop-sync/1.8/config/index.md
  desktop-sync/latest/config/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#559 [DOCS-6605] Update Supported platforms for Desktop Sync 1.9
  desktop-sync/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#554 [DOCS-6622] Add Dark mode to Outlook Integration 2.9
  microsoft-outlook/2.4/config/index.md
  microsoft-outlook/2.5/config/index.md
  microsoft-outlook/2.6/config/index.md
  microsoft-outlook/2.7/config/index.md
  microsoft-outlook/2.8/config/index.md
  microsoft-outlook/latest/config/index.md
Labels: PR: partially-approved, next release :arrow_right:

#561 [DOCS-6556] Add feature - Include all files and sub-folders
  desktop-sync/images/setup-1.9.png
  desktop-sync/images/setup-mac-1.9.png
  desktop-sync/latest/install/index.md
  desktop-sync/latest/using/select-to-sync.md
Labels: PR: reviewed-approved, next release :arrow_right:

#555 [DOCS-6623] Add storeFilesFromDesktop config option
  microsoft-outlook/latest/config/index.md
Labels: PR: partially-approved, next release :arrow_right:

#556 [DOCS-6565] - Add data model
  _data/toc/process-automation.yaml
  process-automation/images/data-model.png
  process-automation/images/ref-data-models.png
  process-automation/latest/model/data-models.md
  process-automation/latest/model/index.md
Labels: PR: partially-approved

#557 [DOCS-6607] Update Supported platforms for Outlook Integration 2.9
  microsoft-outlook/latest/install/index.md
  microsoft-outlook/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#563 [DOCS-6507] - Add SITE field
  search-enterprise/latest/using/field.md
  search-enterprise/latest/using/index.md
  search-enterprise/latest/using/unsupported.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#542 [DOCS-6545] - Multi value properties Text adjustment
  search-enterprise/3.0/support/index.md
Labels: PR: unreviewed, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#531 [DOCS-6570] Add list dynamic
  process-automation/latest/model/forms.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#550 [DOCS-6234] AGS Add batching config parameter for Disposition Lifecycle job
  governance-services/7.1/config/index.md
  governance-services/latest/config/index.md
Labels: documentation, PR: unreviewed, PR: partially-approved, next release :arrow_right:

#571 [DOCS-6613] S3 Connector 5.0
  aws-s3/latest/config/direct-access.md
  aws-s3/latest/config/index.md
  aws-s3/latest/index.md
  aws-s3/latest/install/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#572 [DOCS-6626] Azure Connector 3.0
  _data/toc/microsoft-azure.yaml
  microsoft-azure/latest/config/direct-access.md
  microsoft-azure/latest/config/index.md
  microsoft-azure/latest/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#585 [DOCS-6612] Moved solr shard prop config from general solr config to alfresco acs config
  insight-engine/1.4/config/properties.md
  insight-engine/1.4/config/sharding/create.md
  insight-engine/1.4/config/sharding/index.md
  insight-engine/latest/config/properties.md
  insight-engine/latest/config/sharding/create.md
  insight-engine/latest/config/sharding/index.md
Labels: PR: partially-approved, next release :arrow_right:

#562 [DOCS-6546] - Add proximity search
  search-enterprise/latest/using/index.md
  search-enterprise/latest/using/unsupported.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#547 [DOCS-6598] ACS 7.2 Upgrade section
  content-services/7.0/upgrade/index.md
  content-services/7.1/upgrade/index.md
  content-services/images/upgrade-path-7.2.png
  content-services/latest/upgrade/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#584 [DOCS-6652] - Add new description Deactivate user task re-assignment
  process-services/latest/using/process/bpmn.md
Labels: PR: reviewed-approved

#478 ACS-2259 Documentation for date math in range queries.
  docker-compose-o.yml
  search-enterprise/latest/using/index.md
  search-enterprise/latest/using/unsupported.md
Labels: PR: partially-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#577 [DOCS-6478] - Remove TAG support from unsupported
  search-enterprise/latest/using/unsupported.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#578 [DOCS-6531] ACS 7.2 transformer ext point update related to extensive logging - cron exp update
  content-services/latest/develop/repo-ext-points/content-transformers-renditions.md
Labels: PR: unreviewed, next release :arrow_right:

#573 [DOCS-6604] ACS 7.2 What's New page
  content-services/latest/release/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#552 [DOCS-6600] ACS 7.2 Supported platforms page
  content-services/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#575 [DOCS-6599] ACS 7.2 Developer section updates
  _data/toc/content-services.yaml
  content-services/7.1/develop/extension-inspector.md
  content-services/7.1/develop/rest-api-guide/folders-files.md
  content-services/latest/develop/rest-api-guide/cloud-storage-props.md
  content-services/latest/develop/rest-api-guide/folders-files.md
  content-services/latest/develop/rest-api-guide/install.md
  content-services/latest/develop/sdk.md
Labels: PR: unreviewed, next release :arrow_right:

#543 [DOCS-6597] ACS 7.2 Installation section (except Ansible)
  content-services/latest/install/ansible.md
  content-services/latest/install/containers/customize.md
  content-services/latest/install/containers/docker-compose.md
  content-services/latest/install/containers/helm.md
  content-services/latest/install/containers/index.md
  content-services/latest/install/zip/additions.md
  content-services/latest/install/zip/amp.md
  content-services/latest/install/zip/index.md
  content-services/latest/install/zip/tomcat.md
  transform-service/latest/install/index.md
Labels: PR: unreviewed, next release :arrow_right:

#579 DOCS-6563 - Mediation file update
  search-enterprise/latest/config/index.md
Labels: PR: partially-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#591 [DOCS-6640] Glacier impact on ACS 7.2 docs
  content-services/latest/admin/content-stores.md
Labels: PR: reviewed-approved, next release :arrow_right:

#574 [DOCS-6423] Add PATH setup
  _data/toc/search-enterprise.yaml
  search-enterprise/latest/using/path.md
  search-enterprise/latest/using/unsupported.md
Labels: PR: partially-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#592 [DOCS-6562] Remove old Glacier info in the docs (AGS, S3, ADW, Glacier)
  _data/toc/digital-workspace.yaml
  aws-glacier/2.0/config/index.md
  aws-glacier/2.0/install/index.md
  aws-glacier/2.0/using/index.md
  aws-glacier/2.1/config/index.md
  aws-glacier/2.1/install/index.md
  aws-glacier/2.1/using/index.md
  aws-glacier/latest/config/index.md
  aws-glacier/latest/index.md
  aws-glacier/latest/install/index.md
  aws-glacier/latest/using/index.md
  aws-s3/latest/config/index.md
  aws-s3/latest/using/faq.md
  digital-workspace/latest/governance/archiving.md
  digital-workspace/latest/governance/index.md
  governance-services/latest/using/worm.md
Labels: PR: partially-approved, next release :arrow_right:

#586 [DOCS-6621] Alfresco Office Services 1.4.1
  microsoft-office/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#590 [DOCS-6547] - Add new introduction
  process-automation/latest/index.md
Labels: PR: partially-approved, next release :arrow_right:

#595 [DOCS-6644] Fix links to ACS 7.1 in Glacier docs
  aws-glacier/latest/config/index.md
  aws-glacier/latest/install/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#594 [DOCS-6658] - Remove Oracle connector
  process-automation/latest/model/connectors/database.md
Labels: PR: reviewed-approved, next release :arrow_right:

#597 [DOCS-6621] - Updated AOS 1.4.1 to be compatible with ACS 7.2 only
  microsoft-office/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#600 [DOCS-6661] Fix ADW docs - remove mention of archived content
  digital-workspace/latest/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#598 [DOCS-6648] - Adjust troubleshooting section
  _data/toc/search-enterprise.yaml
  search-enterprise/latest/using/troubleshooting.md
  search-enterprise/latest/using/unsupported.md
Labels: PR: reviewed-approved

#204 Update security.md
  content-services/6.2/admin/security.md
Labels: PR: reviewed-approved

#602 [DOCS-6312] Correct csrf.filter.referer config in ACS docs
  content-services/6.0/admin/security.md
  content-services/6.1/admin/security.md
  content-services/7.0/admin/security.md
  content-services/7.1/admin/security.md
  content-services/community/admin/security.md
  content-services/latest/admin/security.md
Labels: PR: partially-approved

#587 Update Ansible doc for 2.0.0
  content-services/latest/install/ansible.md
Labels: PR: reviewed-approved, next release :arrow_right:
