Repository Alfresco/docs-alfresco, pull requests merged in 2022-06, with the labels that each got.

#677 [DOCS-6757] Remove ACS 7.1 duplicate entry in table of contents
  _data/toc/content-services.yaml
Labels: PR: unreviewed

#654 [DOCS-6734] Updated sfs endpoint ATS Zip install config
  transform-service/1.2/install/index.md
  transform-service/1.3/install/index.md
  transform-service/1.4/install/index.md
  transform-service/latest/install/index.md
Labels: PR: reviewed-approved

#659 [DOCS-6741] Alfresco Intelligence Services 1.4.4
  content-services/latest/support/index.md
  intelligence-services/1.3/config/comprehend.md
  intelligence-services/1.3/index.md
  intelligence-services/1.3/install/index.md
  intelligence-services/1.3/using/index.md
  intelligence-services/latest/config/comprehend.md
  intelligence-services/latest/config/index.md
  intelligence-services/latest/index.md
  intelligence-services/latest/install/index.md
  intelligence-services/latest/support/index.md
Labels: PR: reviewed-approved

#660 [DOCS-6625] Remove Process Workspace from APS 1.10 onwards
  _data/toc/process-services.yaml
  process-services/1.10/install/container.md
  process-services/1.10/install/index.md
  process-services/1.10/install/manual.md
  process-services/1.10/support/index.md
  process-services/1.10/using/index.md
  process-services/1.10/using/workspace.md
  process-services/1.11/config/content.md
  process-services/1.11/install/container.md
  process-services/1.11/install/index.md
  process-services/1.11/install/manual.md
  process-services/1.11/support/index.md
  process-services/1.11/using/index.md
  process-services/1.11/using/workspace.md
  process-services/1.9/install/manual.md
  process-services/1.9/using/index.md
  process-services/2.0/config/content.md
  process-services/2.0/install/container.md
  process-services/2.0/install/index.md
  process-services/2.0/install/manual.md
  process-services/2.0/support/index.md
  process-services/2.0/using/index.md
  process-services/2.0/using/workspace.md
  process-services/2.1/config/content.md
  process-services/2.1/install/container.md
  process-services/2.1/install/index.md
  process-services/2.1/install/manual.md
  process-services/2.1/support/index.md
  process-services/2.1/using/index.md
  process-services/2.1/using/workspace.md
  process-services/2.2/config/content.md
  process-services/2.2/install/container.md
  process-services/2.2/install/index.md
  process-services/2.2/install/manual.md
  process-services/2.2/support/index.md
  process-services/2.2/using/index.md
  process-services/2.2/using/workspace.md
  process-services/latest/config/content.md
  process-services/latest/install/container.md
  process-services/latest/install/index.md
  process-services/latest/install/manual.md
  process-services/latest/support/index.md
  process-services/latest/using/index.md
  process-services/latest/using/workspace.md
Labels: PR: partially-approved

#675 [DOCS-6754] Adding page for add T-Engine to T-Router to ATS 1.5
  _data/toc/transform-service.yaml
  transform-service/latest/config/add-tengine-trouter.md
Labels: PR: reviewed-approved

#646 [DOCS-6731] Alfresco Transform Service (ATS) 1.5.3
  transform-service/latest/config/index.md
  transform-service/latest/install/index.md
  transform-service/latest/support/index.md
Labels: PR: reviewed-approved

#652 [DOCS-6719] Use AuthNegotiateDelegateAllowlist instead of AuthNegotiateDelegateWhitelist for Chrome
  content-services/5.2/admin/auth-sync.md
  content-services/6.0/admin/auth-sync.md
  content-services/6.1/admin/auth-sync.md
  content-services/6.2/admin/auth-sync.md
  content-services/7.0/admin/auth-sync.md
  content-services/7.1/admin/auth-sync.md
  content-services/latest/admin/auth-sync.md
Labels: PR: reviewed-approved

#681 [DOCS-6742] - Alfresco Search Enterprise 3.1.1
  search-enterprise/latest/admin/index.md
  search-enterprise/latest/support/index.md
Labels: PR: partially-approved, DO NOT MERGE 🙅🏻‍♂️

#648 [DOCS-6725] - Add new comment field info
  process-automation/latest/admin/release.md
  process-automation/latest/model/projects.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#691 [DOCS-6728] - Add validation message
  process-automation/latest/model/authentication.md
Labels: PR: reviewed-approved

#690 [DOCS-6732] - Add Groups Restriction
  process-automation/latest/model/forms.md
Labels: PR: reviewed-approved

#667 [DOCS-6724] - Add initial instructions
  process-automation/images/form-editor.png
  process-automation/latest/model/forms.md
Labels: PR: partially-approved, DO NOT MERGE 🙅🏻‍♂️

#689 [DOCS-6760][DOCS-6772] Update for Desktop Sync 1.11 compatibility
  content-services/7.0/support/index.md
  content-services/7.1/support/index.md
  content-services/latest/support/index.md
Labels: PR: unreviewed, next release :arrow_right:

#683 [DOCS-6760] Update Supported platforms for Desktop Sync 1.11
  desktop-sync/latest/support/index.md
Labels: PR: unreviewed, next release :arrow_right:

#692 [DOCS-6727] - Add image for services
  process-automation/images/monitoring-dashboard.png
  process-automation/latest/admin/release.md
Labels: PR: reviewed-approved

#680 [DOCS-6737] Updates for Identity Service 1.8 release
  identity-service/1.1/tutorial/sso/ldap.md
  identity-service/1.1/tutorial/sso/saml.md
  identity-service/1.2/tutorial/sso/ldap.md
  identity-service/1.2/tutorial/sso/saml.md
  identity-service/1.3/tutorial/sso/ldap.md
  identity-service/1.3/tutorial/sso/saml.md
  identity-service/1.4/tutorial/sso/ldap.md
  identity-service/1.4/tutorial/sso/saml.md
  identity-service/1.5/tutorial/sso/ldap.md
  identity-service/1.5/tutorial/sso/saml.md
  identity-service/1.6/tutorial/sso/ldap.md
  identity-service/1.6/tutorial/sso/saml.md
  identity-service/1.7/tutorial/sso/ldap.md
  identity-service/1.7/tutorial/sso/saml.md
  identity-service/latest/config/index.md
  identity-service/latest/install/zip/index.md
  identity-service/latest/tutorial/sso/ldap.md
  identity-service/latest/tutorial/sso/saml.md
  identity-service/latest/upgrade/index.md
Labels: PR: partially-approved, next release :arrow_right:

#695 [DOCS-6759][DOCS-6772] Update for Identity Service 1.8 compatibility
  content-services/7.1/support/index.md
  content-services/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#686 [DOCS-6740] Alfresco Content Connector for Salesforce 2.3.5
  salesforce/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#698 [DOCS-6761] Adjust Supported platforms for ADW version
  content-services/7.0/support/index.md
  content-services/7.1/support/index.md
  content-services/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#697 [DOCS-6794] Fixed enterprise docker image names in SDK 4.4 pom.xml config
  content-services/latest/develop/sdk.md
Labels: PR: reviewed-approved

#687 [DOCS-6755] - Search Enterprise zero downtime upgrade
  search-enterprise/images/add-empty-elasticsearch.png
  search-enterprise/images/final-re-Indexing.png
  search-enterprise/images/index-creation.png
  search-enterprise/images/initial-environment.png
  search-enterprise/images/initial-re-indexing.png
  search-enterprise/images/mirror-acs-environment.png
  search-enterprise/images/shutdown-mirrored.png
  search-enterprise/images/shutdown-solr.png
  search-enterprise/images/start-live-indexing.png
  search-enterprise/images/switch-elasticsearch.png
  search-enterprise/latest/upgrade/index.md
Labels: PR: partially-approved, next release :arrow_right:
