Repository Alfresco/docs-alfresco, pull requests merged in 2022-04, with the labels that each got.

#609 [DOCS-6689] Support Handbook - update link in Support Hours page
  support/latest/hours.md
Labels: PR: reviewed-approved

#599 [DOCS-6659] - Correct note
  insight-engine/latest/support/index.md
Labels: PR: reviewed-approved

#606 [DOCS-6678] - Add process details visibility
  process-automation/latest/using/index.md
Labels: PR: partially-approved

#605 [MNT-22934] Add note about bean definition character limit
  content-services/latest/develop/repo-ext-points/bootstrap-content.md
Labels: PR: reviewed-approved

#613 [DOCS-6692] - Remove unwanted process sentence
  process-automation/latest/using/index.md
Labels: PR: reviewed-approved

#611 [MNT-21434] Mention Outlook license persistence in install page
  microsoft-outlook/latest/install/index.md
Labels: PR: reviewed-approved

#622 [DOCS-6677] - Add new Docusign info
  process-automation/latest/model/connectors/docusign.md
Labels: PR: unreviewed, DO NOT MERGE 🙅🏻‍♂️

#623 [DOCS-6629] Apply Hyland Documentation Notice
  _includes/footer.html
  documentation-notice.md
  terms.md
Labels: PR: unreviewed

#620 [DOCS-6691] Pipeline improvement - reduce sandbox workflow duration
  .github/workflows/sandbox.yml
Labels: PR: reviewed-approved

#624 [DOCS-6665] Fix <tokenized> typo in Content Model Extension Point docs
  content-services/5.2/develop/repo-ext-points/content-model.md
  content-services/6.0/develop/repo-ext-points/content-model.md
  content-services/6.1/develop/repo-ext-points/content-model.md
  content-services/6.2/develop/repo-ext-points/content-model.md
  content-services/7.0/develop/repo-ext-points/content-model.md
  content-services/7.1/develop/repo-ext-points/content-model.md
  content-services/latest/develop/repo-ext-points/content-model.md
Labels: PR: reviewed-approved

#615 [DOCS-6707] FreeMarker ${..} entries must be escaped in Spring context files
  content-services/5.2/develop/repo-ext-points/scheduled-jobs.md
  content-services/6.0/develop/repo-ext-points/scheduled-jobs.md
  content-services/6.1/develop/repo-ext-points/scheduled-jobs.md
  content-services/6.2/develop/repo-ext-points/scheduled-jobs.md
  content-services/7.0/develop/repo-ext-points/scheduled-jobs.md
  content-services/7.1/develop/repo-ext-points/scheduled-jobs.md
  content-services/latest/develop/repo-ext-points/scheduled-jobs.md
Labels: PR: reviewed-approved, tracked

#475 [MNT-22706] Apply recommended patch needs a value of false
  content-services/latest/upgrade/index.md
Labels: PR: reviewed-approved, tracked

#607 [DOCS-6669] - Add restore release option
  process-automation/latest/model/projects.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#612 [DOCS-6674] - Add process category info
  process-automation/latest/model/processes/index.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#621 [DOCS-6675] - Add new parameters and auth types
  process-automation/latest/model/authentication.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#610 [DOCS-6672] - Add autocomplete for APIs and script variables
  process-automation/images/auto-complete.png
  process-automation/latest/model/scripts.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#614 [DOCS-6676] - Add JUEL support expression editor
  process-automation/latest/using/index.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#608 [DOCS-6668] - Add upload release to another environment
  process-automation/latest/admin/release.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#619 [DOCS-6701] New docker-compose file based on Jekyll docker image
  Dockerfile-OLD
  docker-compose-OLD.yml
  docker-compose-a.yml
  docker-compose-o.yml
  docker-compose.yml
Labels: PR: reviewed-approved

#626 [MNT-22706] Fix value for applying recommended patch
  content-services/7.0/upgrade/index.md
  content-services/7.1/upgrade/index.md
  content-services/latest/upgrade/index.md
Labels: PR: partially-approved

#633 [DOCS-6685] - Add permission statement about logged in user
  process-automation/latest/model/scripts.md
Labels: PR: reviewed-approved

#637 [DOCS-6713] Update Support Hours in Support Handbook
  support/latest/hours.md
Labels: PR: reviewed-approved

#630 Revert "[DOCS-6692] - Remove unwanted process sentence"
  process-automation/latest/using/index.md
Labels: PR: reviewed-approved

#634 [DOCS-6681] - Clarify permissions statement
  process-automation/latest/model/connectors/index.md
Labels: PR: reviewed-approved

#636 [DOCS-6684] - Add authentication dropdown info
  process-automation/latest/model/forms.md
Labels: PR: reviewed-approved

#629 [DOCS-6601] Add feature - Remove Local Content
  desktop-sync/latest/index.md
  desktop-sync/latest/using/app-menu.md
Labels: PR: partially-approved, next release :arrow_right:
