Repository Alfresco/docs-alfresco, pull requests merged in 2022-05, with the labels that each got.

#638 [DOCS-6654] - Add due date advanced config
  process-automation/latest/model/processes/bpmn.md
Labels: PR: partially-approved

#640 [DOCS-6578] Add configurable link for Recommended Content panel
  salesforce/latest/using/recommend.md
Labels: PR: partially-approved, next release :arrow_right:

#642 [DOCS-6709] Update compatible versions in Supported platforms pages
  content-services/5.2/support/index.md
  content-services/6.0/support/index.md
  content-services/6.1/support/index.md
  content-services/6.2/support/index.md
  content-services/7.0/support/index.md
  content-services/7.1/support/index.md
  content-services/latest/support/index.md
Labels: PR: unreviewed, next release :arrow_right:

#540 [DOCS-6578] Alfresco Content Connector for Salesforce 2.3.4
  salesforce/latest/support/index.md
  salesforce/latest/using/recommend.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#643 [DOCS-6710] MS 365 version bump 1.1.2
  docker-compose.yml
  microsoft-365/latest/install/index.md
  microsoft-365/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#617 [DOCS-6690] ATS 1.5.2
  transform-service/latest/config/index.md
  transform-service/latest/index.md
  transform-service/latest/install/index.md
  transform-service/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#641 [DOCS-6688] Update compatible versions in Supported platforms pages
  content-services/5.2/support/index.md
  content-services/6.0/support/index.md
  content-services/6.1/support/index.md
  content-services/6.2/support/index.md
  content-services/7.0/support/index.md
  content-services/7.1/support/index.md
  content-services/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#632 [DOCS-6711] Added warning note that sys: namespace is not allowed in ReST API calls for ACS 7.1 and 7.2
  content-services/7.1/develop/rest-api-guide/folders-files.md
  content-services/latest/develop/rest-api-guide/folders-files.md
Labels: PR: reviewed-approved, next release :arrow_right:

#644 DOCS-6730 - Add images and configuration text
  process-automation/images/custom-configuration.png
  process-automation/images/logs-failures.png
  process-automation/images/settings.png
  process-automation/images/start.png
  process-automation/images/status-active.png
  process-automation/images/trigger.png
  process-automation/latest/model/connectors/docusign.md
  process-automation/latest/model/connectors/teams.md
Labels: PR: reviewed-approved

#645 [DOCS-6723] - Add new content/process
  process-automation/latest/model/interfaces.md
Labels: PR: reviewed-approved

#653 [DOCS-6732] - Add Groups Restriction
  process-automation/latest/model/forms.md
Labels: PR: reviewed-approved

#663 [DOCS-6744] Make Alfresco/Hyland navbar logo responsive
  assets/css/main.css
Labels: PR: reviewed-approved

#658 [AAE-8650] fix swagger ui url
  process-automation/latest/develop/index.md
Labels: PR: partially-approved

#647 [DOCS-6714] Removed SDK version mention in Azure Connector product home pages
  microsoft-azure/1.1/index.md
  microsoft-azure/1.2/index.md
  microsoft-azure/2.0/index.md
  microsoft-azure/2.1/index.md
  microsoft-azure/latest/index.md
Labels: PR: reviewed-approved

#666 [DOCS-6541] Fix typo in SAP docs - Install SAP Connector
  sap/5.0/install/index.md
Labels: PR: reviewed-approved

#298 [DOCS-6746] Custom facets : Missing \ in properties qnames
  search-services/1.3/config/filtered.md
Labels: PR: reviewed-approved, tracked, search-sie

#670 [DOCS-6746] Fix default and custom filtered search configuration properties
  insight-engine/1.0/config/filtered.md
  insight-engine/1.1/config/filtered.md
  insight-engine/1.4/config/filtered.md
  insight-engine/latest/config/filtered.md
  search-services/1.4/config/filtered.md
  search-services/latest/config/filtered.md
Labels: PR: reviewed-approved

#674 Revert "[DOCS-6732] - Add Groups Restriction"
  process-automation/latest/model/forms.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#673 Revert "[DOCS-6728] - Add validation message"
  process-automation/latest/model/authentication.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#672 Revert "[DOCS-6727] - Add image for services"
  process-automation/images/monitoring-dashboard.png
  process-automation/latest/admin/release.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#671 Revert "[DOCS-6723] - Add new content/process"
  process-automation/latest/model/interfaces.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#657 [DOCS-6736] - Add new setting and Image
  process-automation/images/settings.png
  process-automation/latest/model/connectors/docusign.md
Labels: PR: reviewed-approved

#538 [DOCS-6576] Alfresco Control Center 7.2
  _data/toc/content-services.yaml
  content-services/latest/admin/control-center.md
  content-services/latest/admin/share-admin-tools.md
  content-services/latest/admin/users-groups.md
Labels: PR: partially-approved, next release :arrow_right:
