Repository Alfresco/docs-alfresco, pull requests merged in 2022-09, with the labels that each got.

#775 [DOCS-6879] Replace security email address in Support Handbook
  support/latest/policies/security.md
Labels: PR: reviewed-approved

#779 Fix final note in Alfresco Search Services upgrade page
  search-services/latest/upgrade/index.md
Labels: PR: reviewed-approved

#780 [DOCS-6909] - Correct code examples
  search-enterprise/3.0/install/index.md
  search-enterprise/latest/install/index.md
Labels: PR: reviewed-approved

#777 [DOCS-6583] - Remove Plain HTTP
  insight-engine/latest/config/properties.md
  insight-engine/latest/install/options.md
  search-services/latest/config/properties.md
  search-services/latest/install/options.md
  search-services/latest/upgrade/migrate.md
Labels: PR: reviewed-approved

#773 [DOCS-6306] Identity Service clean up
  identity-service/1.1/tutorial/sso/kerberos.md
  identity-service/1.1/tutorial/sso/ldap.md
  identity-service/1.1/tutorial/sso/saml.md
  identity-service/1.2/install/k8s/index.md
  identity-service/1.2/install/zip/index.md
  identity-service/1.2/tutorial/sso/kerberos.md
  identity-service/1.2/tutorial/sso/ldap.md
  identity-service/1.2/tutorial/sso/saml.md
  identity-service/1.2/upgrade/index.md
  identity-service/1.3/install/k8s/index.md
  identity-service/1.3/install/zip/index.md
  identity-service/1.3/tutorial/sso/kerberos.md
  identity-service/1.3/tutorial/sso/ldap.md
  identity-service/1.3/tutorial/sso/saml.md
  identity-service/1.3/upgrade/index.md
  identity-service/1.4/install/k8s/index.md
  identity-service/1.4/install/zip/index.md
  identity-service/1.4/tutorial/sso/kerberos.md
  identity-service/1.4/tutorial/sso/ldap.md
  identity-service/1.4/tutorial/sso/saml.md
  identity-service/1.4/upgrade/index.md
  identity-service/1.5/install/k8s/index.md
  identity-service/1.5/install/zip/index.md
  identity-service/1.5/tutorial/sso/kerberos.md
  identity-service/1.5/tutorial/sso/ldap.md
  identity-service/1.5/tutorial/sso/saml.md
  identity-service/1.6/install/k8s/index.md
  identity-service/1.6/install/zip/index.md
  identity-service/1.6/tutorial/sso/kerberos.md
  identity-service/1.6/tutorial/sso/ldap.md
  identity-service/1.6/tutorial/sso/saml.md
  identity-service/1.7/install/k8s/index.md
  identity-service/1.7/tutorial/sso/kerberos.md
  identity-service/1.7/tutorial/sso/ldap.md
  identity-service/1.7/tutorial/sso/saml.md
  identity-service/latest/install/k8s/index.md
  identity-service/latest/tutorial/sso/kerberos.md
  identity-service/latest/tutorial/sso/ldap.md
  identity-service/latest/tutorial/sso/saml.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#762 [DOCS-6861] Add Desktop Sync 1.13 compatibility
  content-services/7.0/support/index.md
  content-services/7.1/support/index.md
  content-services/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#781 [DOCS-6871] Update release summary for Desktop Sync 1.13
  desktop-sync/latest/index.md
Labels: PR: partially-approved, next release :arrow_right:

#788 [DOCS-6916] Add Digital Workspace 3.0 compatibility
  content-services/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#784 [DOCS-6865] Mobile Workspace Tasks
  mobile-workspace/latest/using/index.md
Labels: PR: partially-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#785 [DOCS-6912] Mobile Workspace 1.4 ACS SP compatibility
  content-services/6.2/support/index.md
  content-services/7.0/support/index.md
  content-services/7.1/support/index.md
  content-services/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#782 [DOCS-6870] Update Content Services Supported Platforms pages
  content-services/6.2/support/index.md
  content-services/7.0/support/index.md
  content-services/7.1/support/index.md
  content-services/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#783 [DOCS-6795] Add Security Marks to ADW
  _data/toc/digital-workspace.yaml
  digital-workspace/images/security-controls.png
  digital-workspace/images/security-marks.png
  digital-workspace/latest/governance/security.md
Labels: PR: partially-approved, next release :arrow_right:

#793 [DOCS-6865] Alfresco Mobile Workspace 1.4
  mobile-workspace/latest/config/index.md
  mobile-workspace/latest/using/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#792 [DOCS-6886] Add new User Role
  process-automation/latest/admin/users.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#786 [DOCS-6891] - Add Display Rich Text
  process-automation/images/payslip.png
  process-automation/latest/model/forms.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#797 Solr Communication Method Secret with ACS 7.2
  search-services/latest/install/options.md
Labels: PR: reviewed-approved

#791 [DOCS-6898] Add new radio buttons info
  process-automation/latest/model/forms.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#787 [DOCS-6892] Add download audit events
  process-automation/latest/admin/monitor.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#789 [DOCS-6890] Add process instances delete
  process-automation/latest/admin/monitor.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#795 [DOCS-6896] Add search feature
  process-automation/images/search-projects.png
  process-automation/latest/model/projects.md
Labels: DO NOT MERGE 🙅🏻‍♂️

#798 [DOCS-6925] Add applications list section
  process-automation/latest/admin/monitor.md
  process-automation/latest/develop/index.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️
