Repository Alfresco/docs-alfresco, pull requests merged in 2022-12, with the labels that each got.

#894 [DOCS-6936] [DOCS-6941] [DOCS-6940] Include support for ACS 7.2
  content-services/7.2/support/index.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#806 [DOCS-6957] Update authentication docs
  process-automation/images/authentication-delete.png
  process-automation/latest/model/authentication.md
Labels: PR: partially-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#885 [DOCS-7022] Select multiple User tasks
  process-automation/latest/admin/monitor.md
Labels: PR: partially-approved

#893 [DOCS-6981] Alfresco Process Services 2.3.5 Fixed typos
  process-services/latest/admin/index.md
  process-services/latest/support/index.md
Labels: PR: partially-approved, DO NOT MERGE 🙅🏻‍♂️

#896 [DOCS-7047] Improve navigation for SSO Guides
  _data/toc/identity-service-tutorial.yaml
  identity-service/latest/tutorial/index.md
  identity-service/latest/tutorial/sso-v1/index.md
  identity-service/latest/tutorial/sso/index.md
Labels: PR: partially-approved

#898 [DOCS-7023] Use RequestPayload parameter
  process-automation/latest/model/connectors/rest.md
Labels: PR: reviewed-approved

#897 [DOCS-6991] Add Capture assignee
  process-automation/latest/model/processes/index.md
Labels: PR: partially-approved, DO NOT MERGE 🙅🏻‍♂️

#809 [DOCS-6978] Fix reference to missing class (since Search Services 2.0)
  search-services/latest/config/replication.md
Labels: PR: reviewed-approved, tracked
