Repository Alfresco/docs-alfresco, pull requests merged in 2023-05, with the labels that each got.

#981 [DOCS-7099] Content Services 7.4 Add description to disable event2
  content-services/latest/develop/oop-ext-points/events.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#984 [DOCS-7219] Remove unsupported AFS
  _data/toc/enterprise-viewer.yaml
  content-accelerator/images/aca-control-types.png
  content-accelerator/images/aca-userguide-autocomplete-field.png
  content-accelerator/images/aca-userguide-proximity-date-range.png
  content-accelerator/images/aca-userguide-repeating-field.png
  content-accelerator/images/aca-userguide-required-field.png
  content-accelerator/images/aca-userguide-required-fields-statisfied.png
  content-accelerator/images/aca-userguide-still-needs-required-fields-or-validation.png
  content-accelerator/images/aca-userguide-uneditable-field.png
  content-accelerator/images/aca-userguide-validation-error.png
  content-accelerator/images/form-type-selection.png
  content-accelerator/images/object-type-config.png
  content-accelerator/latest/configure/actions.md
  content-accelerator/latest/configure/activewizard.md
  content-accelerator/latest/configure/admin-guide.md
  content-accelerator/latest/configure/alfresco-audit-configuration.md
  content-accelerator/latest/configure/autofile.md
  content-accelerator/latest/configure/email-configuration.md
  content-accelerator/latest/configure/integrations-and-addons.md
  content-accelerator/latest/configure/limitations.md
  content-accelerator/latest/configure/notifications-and-notes.md
  content-accelerator/latest/configure/oc-property-overrides.md
  content-accelerator/latest/configure/other-aca-admin-configs.md
  content-accelerator/latest/develop/content-accelerator-for-claims-management.md
  content-accelerator/latest/develop/content-accelerator-for-pnp-management.md
  content-accelerator/latest/develop/extension-content-accelerator.md
  content-accelerator/latest/index.md
  content-accelerator/latest/install/install-guide.md
  content-accelerator/latest/install/installation-requirements.md
  content-accelerator/latest/install/sso.md
  content-accelerator/latest/install/upgrading.md
  content-accelerator/latest/using/user-guide.md
  enterprise-viewer/latest/config/actions.md
  enterprise-viewer/latest/config/collaboration.md
  enterprise-viewer/latest/config/faq.md
  enterprise-viewer/latest/config/files.md
  enterprise-viewer/latest/config/overlay.md
  enterprise-viewer/latest/config/performance.md
  enterprise-viewer/latest/config/suggested-redact.md
  enterprise-viewer/latest/develop/adf.md
  enterprise-viewer/latest/develop/integrations.md
  enterprise-viewer/latest/index.md
  enterprise-viewer/latest/install/adf.md
  enterprise-viewer/latest/install/aevt.md
  enterprise-viewer/latest/install/index.md
  enterprise-viewer/latest/install/upgrade.md
  enterprise-viewer/latest/support/index.md
  enterprise-viewer/latest/using/index.md
  search-enterprise/latest/using/unsupported.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#987 [DOCS-7179] Add new environment properties
  digital-workspace/latest/config/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#991 [DOCS-7215] Correct typo defaults
  content-services/7.2/install/ansible.md
  content-services/7.3/install/ansible.md
  content-services/latest/install/ansible.md
Labels: PR: reviewed-approved, next release :arrow_right:

#968 [DOCS-7202] Remove AGS being unsupported
  search-enterprise/latest/using/unsupported.md
Labels: PR: unreviewed, next release :arrow_right:

#972 [DOCS-6502] Unsupported multilingual removed
  _data/toc/search-enterprise.yaml
  search-enterprise/latest/config/language.md
  search-enterprise/latest/index.md
  search-enterprise/latest/using/unsupported.md
Labels: PR: partially-approved, next release :arrow_right:

#1005 [DOCS-7211] 365-edits
  microsoft-365/1.1/install/index.md
  microsoft-365/latest/install/index.md
  microsoft-365/latest/support/index.md
Labels: next release :arrow_right:

#989 [DOCS-7213] ACS 7.4 Admin - Hazelcast security
  content-services/latest/admin/cluster.md
Labels: PR: partially-approved, next release :arrow_right:

#884 [DOCS-7035] Add support for multiple databases in Search Enterprise
  search-enterprise/latest/admin/index.md
  search-enterprise/latest/config/index.md
Labels: PR: partially-approved, next release :arrow_right:

#990 [DOCS-7218] Add WCAG information
  digital-workspace/latest/index.md
Labels: PR: unreviewed, next release :arrow_right:

#992 [DOCS-7214] ACS 7.4 Keycloak Adapter migration
  content-services/latest/admin/auth-sync.md
Labels: PR: reviewed-approved, next release :arrow_right:

#979 [DOCS-7208] Add Governance Services Community 7.4
  governance-services/community/develop/index.md
  governance-services/community/install/docker.md
  governance-services/community/install/uninstall.md
  governance-services/community/install/zip.md
Labels: PR: unreviewed, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#1006 [DOCS-7223] Add warning using the JMX interface for Content Services 7.4
  content-services/latest/config/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#1004 [DOCS-7220] Add new Rocky Linux reference
  process-services/latest/support/index.md
Labels: next release :arrow_right:

#994 [DOCS-7129] Add Log4j2 Migration Guide
  _data/toc/content-services.yaml
  content-services/latest/upgrade/log4j2-migrate.md
Labels: PR: partially-approved, next release :arrow_right:

#1008 [DOCS-7169] Add Search Enterprise 3.3 compatibility with ACS
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#980 [DOCS-7170] Extension Inspector update to version 1.6.0
  content-services/latest/develop/extension-inspector.md
Labels: PR: partially-approved, next release :arrow_right:

#993 [DOCS-7014] Add Tags and Categories (ADW 4.0)
  content-services/latest/admin/control-center.md
  digital-workspace/latest/governance/security.md
Labels: PR: partially-approved, next release :arrow_right:

#1009 [DOCS-7236] Add Digital Workspace 4.0 compatibility with ACS
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1010 [DOCS-7237] Add Tags and Categories feature to ACS 7.4 docs
  _data/toc/content-services.yaml
  content-services/latest/admin/control-center.md
  content-services/latest/using/content/tags-categories.md
Labels: next release :arrow_right:

#1012 [DOCS 7189] Content Services 7.4 Supported Platforms
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1011 [DOCS-7191] Updated community ZIP file links to 7.4
  content-services/community/install/zip/amp.md
  content-services/community/install/zip/index.md
  content-services/community/install/zip/tomcat.md
  content-services/latest/upgrade/index.md
Labels: PR: partially-approved, next release :arrow_right:

#998 [DOCS-7128] ACS 7.4 log4j2 upgrade
  content-services/latest/admin/audit.md
  content-services/latest/admin/auth-sync.md
  content-services/latest/admin/cluster.md
  content-services/latest/admin/content-stores.md
  content-services/latest/admin/import-transfer.md
  content-services/latest/admin/index.md
  content-services/latest/admin/jmx-reference.md
  content-services/latest/admin/query-accelerator.md
  content-services/latest/admin/security.md
  content-services/latest/admin/troubleshoot.md
  content-services/latest/config/file-servers.md
  content-services/latest/config/repository.md
  content-services/latest/develop/extension-packaging.md
  content-services/latest/develop/reference/java-foundation-ref.md
  content-services/latest/develop/repo-ext-points/audit-log.md
  content-services/latest/develop/repo-ext-points/metadata-extractors.md
  content-services/latest/develop/sdk.md
  content-services/latest/install/containers/helm.md
Labels: PR: reviewed-approved, next release :arrow_right:

#1013 [DOCS 7193] Content Services What's New updates
  content-services/latest/release/index.md
Labels: next release :arrow_right:

#971 [DOCS-7082] [DOCS-7189] Update ACS 7.4 supported platforms
  content-services/7.2/support/index.md
  content-services/7.3/support/index.md
  content-services/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#1027 [DOCS-7149] Add Periodic Review config
  content-accelerator/latest/install/upgrading.md
Labels: next release :arrow_right:
