Repository Alfresco/docs-alfresco, pull requests merged in 2023-11, with the labels that each got.

#1177 [DOCS-7432] Add Healthcheck configuration
  search-enterprise/images/health-check.png
  search-enterprise/latest/admin/index.md
Labels: next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#1188 [DOCS-7407] Add S3 Connector 6.0 compatibility with ACS 23.1
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1189 [DOCS-7394] Add Azure Connector 4.0 compatibility with ACS 23.1
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1190 [DOCS-7279] Add scheduled job to remove dead cluster nodes from the database
  content-services/latest/develop/repo-ext-points/scheduled-jobs.md
Labels: next release :arrow_right:

#1192 [DOCS-7422] Update upgrade guidance for ACS 23.1
  content-services/images/upgrade-path-23.1.png
  content-services/latest/upgrade/index.md
Labels: next release :arrow_right:

#1195 [DOCS-7294] Update compatible Tomcat + module versions
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1175 [DOCS-7385] Add Alfresco Content Connector for Azure 4.0 docs
  _config.yml
  _data/toc/microsoft-azure.yaml
  microsoft-azure/3.2/admin/index.md
  microsoft-azure/3.2/config/direct-access.md
  microsoft-azure/3.2/config/index.md
  microsoft-azure/3.2/index.md
  microsoft-azure/3.2/install/index.md
  microsoft-azure/3.2/support/index.md
  microsoft-azure/latest/config/index.md
  microsoft-azure/latest/index.md
  microsoft-azure/latest/install/index.md
  microsoft-azure/latest/support/index.md
Labels: next release :arrow_right:

#1194 [DOCS-7446] Update supported version of Tomcat in Config docs
  content-services/latest/config/repository.md
Labels: next release :arrow_right:

#1184 [DOCS-7451] Add language support update
  search-enterprise/latest/config/language.md
Labels: next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#1180 [DOCS-7437] Configure dynamic view
  digital-workspace/latest/config/index.md
Labels: next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#1153 [DOCS-6908] Add new DocuSign connector information
  process-automation/latest/model/connectors/docusign.md
Labels: DO NOT MERGE 🙅🏻‍♂️

#1070 [ACS-4369] Support for PRIMARYPARENT and PARENT fields.
  search-enterprise/latest/using/unsupported.md
Labels: next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#1199 [DOCS-7423] Add What's New content for ACS 23.1 release
  content-services/latest/release/index.md
Labels: next release :arrow_right:

#1198 [DOCS-7415] Update Install pages
  content-services/latest/install/ansible.md
  content-services/latest/install/containers/customize.md
  content-services/latest/install/containers/docker-compose.md
  content-services/latest/install/containers/helm.md
  content-services/latest/install/zip/additions.md
  content-services/latest/install/zip/amp.md
  content-services/latest/install/zip/index.md
  content-services/latest/install/zip/tomcat.md
Labels: next release :arrow_right:

#1186 [DOCS-7294] Add ACS 23.1 Supported platforms page
  content-services/7.4/support/index.md
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1183 [DOCS-7454] Data Tables widget is available
  process-automation/latest/admin/index.md
  process-automation/latest/model/forms.md
Labels: next release :arrow_right:, need-more-info, DO NOT MERGE 🙅🏻‍♂️

#1207 [DOCS-7383] Add Google Docs Integration 4.0 docs
  _config.yml
  _data/toc/google-drive.yaml
  google-drive/3.4/config/index.md
  google-drive/3.4/index.md
  google-drive/3.4/install/index.md
  google-drive/3.4/support/index.md
  google-drive/latest/install/index.md
  google-drive/latest/support/index.md
Labels: next release :arrow_right:

#1187 [DOCS-7397] Governance Services Community Edition 23.1
  governance-services/community/develop/index.md
  governance-services/community/install/docker.md
  governance-services/community/install/uninstall.md
  governance-services/community/install/zip.md
Labels: next release :arrow_right:

#1203 [DOCS-7418] Add Control Center 8.3
  content-services/latest/admin/control-center.md
Labels: next release :arrow_right:

#1215 [DOCS-7419] Add Control Center 8.3 to 7.4 supported platforms
  content-services/7.4/support/index.md
Labels: DO NOT MERGE 🙅🏻‍♂️

#1216 [DOCS-7393] Update SAP Applications Connector 6.0 compatibility with ACS 23.1
  sap/latest/support/index.md
Labels: next release :arrow_right:

#1220 [DOCS-7414] Add Alfresco Extension Inspector 1.9 in ACS 23.1
  content-services/latest/develop/extension-inspector.md
Labels: next release :arrow_right:

#1224 [DOCS-7430] Add APS Action AMP compatibility in ACS 23.1 docs
  content-services/latest/config/action.md
Labels: next release :arrow_right:

#1217 [DOCS-7435] Add external Hazelcast clustering for ACS 23.1
  content-services/latest/admin/cluster.md
  content-services/latest/admin/jmx-reference.md
  content-services/latest/release/index.md
Labels: next release :arrow_right:

#1234 [DOCS-7484] Change reference to correct version
  search-enterprise/latest/upgrade/index.md
  search-enterprise/latest/using/unsupported.md
Labels: DO NOT MERGE 🙅🏻‍♂️

#1231 [DOCS-7094] Read file content removed
  process-automation/latest/model/connectors/content.md
Labels: PR: reviewed-approved
