Repository Alfresco/docs-alfresco, pull requests merged in 2023-10, with the labels that each got.

#1161 [DOCS-6791] Backup parameter deprecated in SOLR 2.x
  insight-engine/latest/config/sharding/index.md
Labels: DO NOT MERGE 🙅🏻‍♂️

#899 [DOCS-7068] Fix location for cross-locale configuration
  insight-engine/latest/using/sql/syntax.md
  search-services/1.3/using/index.md
  search-services/1.4/using/index.md
  search-services/latest/using/index.md
Labels: tracked

#957 [DOCS-7203] Add reference to pre-indexing considerations
  search-enterprise/3.0/using/index.md
  search-enterprise/3.1/using/index.md
  search-enterprise/latest/using/index.md
Labels: tracked, DO NOT MERGE 🙅🏻‍♂️

#1147 [DOCS-7376] Revise cookie usage in SAML Module docs
  saml-module/latest/config/alfresco.md
Labels: tracked

#1141 [DOCS-7358] Add HR Employee File Management solution to Alfresco Content Accelerator 3.5 docs
  _data/toc/content-accelerator.yaml
  content-accelerator/images/hrefm-create-new-group.png
  content-accelerator/images/hrefm-create-new-hold.png
  content-accelerator/images/hrefm-create-new-role.png
  content-accelerator/images/hrefm-create-new-rule.png
  content-accelerator/images/hrefm-file-plan.png
  content-accelerator/images/hrefm-import-action.png
  content-accelerator/images/hrefm-intro-dashboard1.png
  content-accelerator/images/hrefm-intro-dashboard2.png
  content-accelerator/images/hrefm-required-documents.png
  content-accelerator/images/hrefm-sites-tab.png
  content-accelerator/images/hrefm-unfiled-records-manage-rules.png
  content-accelerator/latest/configure/hr-management.md
  content-accelerator/latest/index.md
  content-accelerator/latest/install/install-guide.md
Labels: next release :arrow_right:

#794 [DOCS-6977] Add AOS Troubleshooting step
  microsoft-office/1.1/admin/index.md
  microsoft-office/1.2/admin/index.md
  microsoft-office/1.3/admin/index.md
  microsoft-office/images/certificate-manager-dialog.png
  microsoft-office/images/import-personal-cert-dialog.png
  microsoft-office/images/import-personal-cert-finalized.png
  microsoft-office/images/import-personal-cert-finish.png
  microsoft-office/images/import-personal-cert-saveas-personal.png
  microsoft-office/images/import-personal-cert-select-dialog.png
  microsoft-office/images/import-personal-cert-selected-dialog.png
  microsoft-office/images/personal-cert-pass-prompt.png
  microsoft-office/images/run-command-dialog.png
  microsoft-office/latest/admin/index.md
Labels: PR: unreviewed, tracked

#1089 [DOCS-7270] Federation Services 3.0 docs updates
  federation-services/images/simple-architecture-3.0.png
  federation-services/latest/config/index.md
  federation-services/latest/index.md
  federation-services/latest/install/index.md
Labels: need-more-info

#1157 [DOCS-7399] Escape parameter values with quotes
  transform-service/latest/install/index.md
Labels: tracked
