Repository Alfresco/docs-alfresco, pull requests merged in 2023-04, with the labels that each got.

#965 [DOCS-7197] Update supported Mac OS version
  desktop-sync/latest/install/index.md
Labels: PR: partially-approved, next release :arrow_right:

#967 [DOCS-7084][DOCS-7187] Update Salesforce 2.4 supported platforms
  salesforce/latest/config/index.md
  salesforce/latest/install/index.md
  salesforce/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#964 [DOCS-7154][DOCS-7156] Update Desktop Sync 1.15 supported platforms
  desktop-sync/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#970 [DOCS 7080] ACS 7.4 JavaScript Execution properties
  content-services/latest/config/repository.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#963 [DOCS-7106] Update Sync Service 3.9 release summary and supported platforms
  sync-service/latest/index.md
  sync-service/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#956 [DOCS-7126] Alfresco Enterprise Viewer 3.5 docs improvements
  _data/toc/enterprise-viewer.yaml
  enterprise-viewer/latest/config/actions.md
  enterprise-viewer/latest/config/collaboration.md
  enterprise-viewer/latest/config/faq.md
  enterprise-viewer/latest/config/files.md
  enterprise-viewer/latest/config/overlay.md
  enterprise-viewer/latest/config/performance.md
  enterprise-viewer/latest/config/suggested-redact.md
  enterprise-viewer/latest/develop/adf.md
  enterprise-viewer/latest/develop/integrations.md
  enterprise-viewer/latest/index.md
  enterprise-viewer/latest/install/adf.md
  enterprise-viewer/latest/install/aevt.md
  enterprise-viewer/latest/install/index.md
  enterprise-viewer/latest/install/upgrade.md
  enterprise-viewer/latest/support/index.md
  enterprise-viewer/latest/using/index.md
Labels: PR: reviewed-approved

#958 [DOCS-7123] Alfresco Content Accelerator 3.5 edits
  content-accelerator/images/aca-control-types.png
  content-accelerator/images/aca-userguide-autocomplete-field.png
  content-accelerator/images/aca-userguide-proximity-date-range.png
  content-accelerator/images/aca-userguide-repeating-field.png
  content-accelerator/images/aca-userguide-required-field.png
  content-accelerator/images/aca-userguide-required-fields-statisfied.png
  content-accelerator/images/aca-userguide-still-needs-required-fields-or-validation.png
  content-accelerator/images/aca-userguide-uneditable-field.png
  content-accelerator/images/aca-userguide-validation-error.png
  content-accelerator/images/form-type-selection.png
  content-accelerator/images/object-type-config.png
  content-accelerator/latest/configure/actions.md
  content-accelerator/latest/configure/activewizard.md
  content-accelerator/latest/configure/admin-guide.md
  content-accelerator/latest/configure/alfresco-audit-configuration.md
  content-accelerator/latest/configure/autofile.md
  content-accelerator/latest/configure/email-configuration.md
  content-accelerator/latest/configure/integrations-and-addons.md
  content-accelerator/latest/configure/limitations.md
  content-accelerator/latest/configure/notifications-and-notes.md
  content-accelerator/latest/configure/oc-property-overrides.md
  content-accelerator/latest/configure/other-aca-admin-configs.md
  content-accelerator/latest/develop/content-accelerator-for-claims-management.md
  content-accelerator/latest/develop/content-accelerator-for-pnp-management.md
  content-accelerator/latest/develop/extension-content-accelerator.md
  content-accelerator/latest/index.md
  content-accelerator/latest/install/install-guide.md
  content-accelerator/latest/install/installation-requirements.md
  content-accelerator/latest/install/sso.md
  content-accelerator/latest/install/upgrading.md
  content-accelerator/latest/using/user-guide.md
Labels: PR: reviewed-approved, next release :arrow_right:

#975 [DOCS-7084][DOCS-7187] Add Salesforce Connector 2.4 compatibility with ACS
  content-services/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#977 [DOCS-7175] Correct 'an' Content Services
  content-services/7.0/develop/reference/surf-framework-ref.md
  content-services/7.0/develop/reference/web-scripts-ref.md
  content-services/7.0/develop/repo-ext-points/content-transformers-renditions.md
  content-services/7.0/develop/repo-ext-points/mimetypes.md
  content-services/7.0/develop/repo-ext-points/module-components.md
  content-services/7.0/develop/repo-ext-points/web-scripts.md
  content-services/7.0/develop/share-ext-points/form-processors.md
  content-services/7.0/develop/software-architecture.md
  content-services/7.0/tutorial/share/doclib.md
  content-services/7.1/develop/reference/surf-framework-ref.md
  content-services/7.1/develop/reference/web-scripts-ref.md
  content-services/7.1/develop/repo-ext-points/content-transformers-renditions.md
  content-services/7.1/develop/repo-ext-points/mimetypes.md
  content-services/7.1/develop/repo-ext-points/module-components.md
  content-services/7.1/develop/repo-ext-points/web-scripts.md
  content-services/7.1/develop/share-ext-points/form-processors.md
  content-services/7.1/develop/software-architecture.md
  content-services/7.1/tutorial/share/doclib.md
  content-services/7.2/develop/reference/surf-framework-ref.md
  content-services/7.2/develop/reference/web-scripts-ref.md
  content-services/7.2/develop/repo-ext-points/content-transformers-renditions.md
  content-services/7.2/develop/repo-ext-points/mimetypes.md
  content-services/7.2/develop/repo-ext-points/module-components.md
  content-services/7.2/develop/repo-ext-points/web-scripts.md
  content-services/7.2/develop/share-ext-points/form-processors.md
  content-services/7.2/develop/software-architecture.md
  content-services/7.2/tutorial/share/doclib.md
  content-services/7.3/develop/reference/surf-framework-ref.md
  content-services/7.3/develop/reference/web-scripts-ref.md
  content-services/7.3/develop/repo-ext-points/content-transformers-renditions.md
  content-services/7.3/develop/repo-ext-points/mimetypes.md
  content-services/7.3/develop/repo-ext-points/module-components.md
  content-services/7.3/develop/repo-ext-points/web-scripts.md
  content-services/7.3/develop/share-ext-points/form-processors.md
  content-services/7.3/tutorial/share/doclib.md
  content-services/latest/develop/reference/surf-framework-ref.md
  content-services/latest/develop/reference/web-scripts-ref.md
  content-services/latest/develop/repo-ext-points/content-transformers-renditions.md
  content-services/latest/develop/repo-ext-points/mimetypes.md
  content-services/latest/develop/repo-ext-points/module-components.md
  content-services/latest/develop/repo-ext-points/web-scripts.md
  content-services/latest/develop/share-ext-points/form-processors.md
  content-services/latest/tutorial/share/doclib.md
Labels: PR: reviewed-approved, next release :arrow_right:

#969 [DOCS-7188] Add UI indicators for space consumed by Alfresco folder
  desktop-sync/1.14/index.md
  desktop-sync/latest/index.md
  desktop-sync/latest/using/app-menu.md
  desktop-sync/latest/using/faq.md
Labels: PR: partially-approved, next release :arrow_right:

#973 [DOCS-7105][DOCS-7106] Add Sync Service 3.9 compatibility with ACS
  content-services/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#974 [DOCS-7154][DOCS-7156] Add Desktop Sync 1.15 compatibility with ACS
  content-services/7.2/support/index.md
  content-services/7.3/support/index.md
  content-services/latest/support/index.md
Labels: PR: unreviewed, next release :arrow_right:
