Repository Alfresco/docs-alfresco, pull requests merged in 2023-08, with the labels that each got.

#1096 [DOCS-7307] Update install, config, and support sections of DTE 2.4 docs
  transformation-engine/2.3/config/index.md
  transformation-engine/2.3/install/msi.md
  transformation-engine/latest/config/index.md
  transformation-engine/latest/install/index.md
  transformation-engine/latest/install/msi.md
  transformation-engine/latest/install/sdk.md
  transformation-engine/latest/support/index.md
Labels: next release :arrow_right:

#1101 [DOCS-7307][DOCS-7308] Add DTE 2.4 compatibility with ACS
  content-services/7.0/support/index.md
  content-services/7.1/support/index.md
  content-services/7.2/support/index.md
  content-services/7.3/support/index.md
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1093 [DOCS-7292] Update supported platforms page for ACS 7.4.1
  content-services/7.0/support/index.md
  content-services/7.1/support/index.md
  content-services/7.2/support/index.md
  content-services/7.3/support/index.md
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1100 [DOCS-7320] Add Alfresco Extension Inspector 1.7
  content-services/7.0/develop/extension-inspector.md
  content-services/7.1/develop/extension-inspector.md
  content-services/7.2/develop/extension-inspector.md
  content-services/7.3/develop/extension-inspector.md
  content-services/latest/develop/extension-inspector.md
Labels: next release :arrow_right:

#1099 [DOCS-7267] Add new parameter
  search-enterprise/latest/config/index.md
Labels: next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#1097 [DOCS-7272] Add new search features
  search-enterprise/latest/using/index.md
  search-enterprise/latest/using/unsupported.md
  search-services/1.3/using/index.md
  search-services/1.4/using/index.md
  search-services/latest/using/index.md
Labels: DO NOT MERGE 🙅🏻‍♂️
