Repository Alfresco/docs-alfresco, pull requests merged in 2023-09, with the labels that each got.

#1128 [DOCS-6946] Removal of PostgreSQL reference
  search-enterprise/latest/admin/index.md
Labels: DO NOT MERGE 🙅🏻‍♂️

#1104 [DOCS-7312] Update install steps for SAP Connector 5.3
  sap/5.2/install/index.md
  sap/latest/admin/reference.md
  sap/latest/index.md
  sap/latest/install/index.md
  sap/latest/support/index.md
Labels: next release :arrow_right:

#1138 [DOCS-7315] Update Supported platforms for SAP applications 5.3
  content-services/7.0/support/index.md
  content-services/7.1/support/index.md
  content-services/7.2/support/index.md
  content-services/7.3/support/index.md
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1144 [DOCS-7348] Update Supported platforms for ADW 4.2
  content-services/latest/support/index.md
Labels: next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#1146 [DOCS-7351] Update Supported platforms for Control Center 7.x and 8.x
  content-services/7.2/support/index.md
  content-services/7.3/support/index.md
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1139 [DOCS-7354] Update Content Services Supported platforms pages
  content-services/7.0/support/index.md
  content-services/7.1/support/index.md
  content-services/7.2/support/index.md
  content-services/7.3/support/index.md
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1150 [DOCS-7375] Add note - ATS 3.0 is compatible with Java 17 only
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1152 [DOCS-7207] Add Environment variables
  search-enterprise/latest/admin/index.md
Labels: DO NOT MERGE 🙅🏻‍♂️
