Repository Alfresco/docs-alfresco, pull requests merged in 2023-12, with the labels that each got.

#1235 [DOCS-7482] Outlook replaced with Calendar connector
  process-automation/latest/model/connectors/outlook.md
Labels: bug

#1242 [DOCS-7433] Update ACA 3.6 compatibility with ACS and configuration
  content-accelerator/latest/install/install-guide.md
  content-accelerator/latest/support/index.md
  content-services/7.2/support/index.md
  content-services/7.3/support/index.md
  content-services/7.4/support/index.md
Labels: next release :arrow_right:

#1250 [DOCS-7486] Disable Autofile
  content-accelerator/3.5/configure/autofile.md
  content-accelerator/latest/configure/autofile.md
Labels: next release :arrow_right:

#1245 [DOCS-7448] Update ACA install guide
  content-accelerator/latest/install/install-guide.md
Labels: next release :arrow_right:

#1256 [DOCS-7489] Add new configuration options for Outlook Integration 2.10
  microsoft-outlook/latest/config/index.md
Labels: PR: draft, next release :arrow_right:

#1251 [DOCS-7450] Update ACA and AEV compatibility with Alfresco Search Enterprise
  search-enterprise/3.3/using/unsupported.md
  search-enterprise/latest/using/unsupported.md
Labels: next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#1261 [DOCS-7509] Update autofiling documentation
  content-accelerator/latest/configure/autofile.md
Labels: next release :arrow_right:

#1264 [DOCS-7511] Fix versions in Content Accelerator and Enterprise Viewer 3.6 docs
  content-accelerator/latest/install/install-guide.md
  enterprise-viewer/latest/install/index.md
Labels: next release :arrow_right:

#1165 [DOCS-7405] Search UI updates in ADW 4.2
  digital-workspace/2.3/config/index.md
  digital-workspace/images/search-user-interface.png
  digital-workspace/latest/config/index.md
Labels: DO NOT MERGE 🙅🏻‍♂️

#1166 [DOCS-7143] Bulk metadata indexing
  search-enterprise/3.2/admin/index.md
  search-enterprise/images/database-configuration.png
  search-enterprise/images/database-statistics.png
Labels: DO NOT MERGE 🙅🏻‍♂️
