Repository Alfresco/docs-alfresco, pull requests merged in 2023-06, with the labels that each got.

#1031 [DOCS-7229] Add 3.5.1 SSL configuration
  enterprise-viewer/latest/install/upgrade.md
Labels: next release :arrow_right:

#1030 [DOCS 7038] Add AEV secureBrowserCookies
  enterprise-viewer/latest/install/index.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#1032 [DOCS 7232] Java 17 Support for AEV 3.5.1
  _data/toc/enterprise-viewer.yaml
  enterprise-viewer/latest/install/index.md
  enterprise-viewer/latest/install/java-support.md
  enterprise-viewer/latest/install/prereqs.md
Labels: next release :arrow_right:

#1034 [DOCS 7232] Java 17 Support for ACA 3.5.1
  _data/toc/content-accelerator.yaml
  content-accelerator/latest/install/install-guide.md
  content-accelerator/latest/install/java-support.md
Labels: next release :arrow_right:

#1023 [DOCS-7139] Alfresco Enterprise Viewer 3.5.1
  _data/toc/enterprise-viewer.yaml
  enterprise-viewer/latest/install/index.md
  enterprise-viewer/latest/install/java-support.md
  enterprise-viewer/latest/install/prereqs.md
  enterprise-viewer/latest/install/upgrade.md
  enterprise-viewer/latest/support/index.md
Labels: next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#966 [DOCS-7162] Add column width section
  process-automation/latest/using/index.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#1021 [DOCS-7138] Alfresco Content Accelerator 3.5.1
  _data/toc/content-accelerator.yaml
  content-accelerator/images/power-promote-options.png
  content-accelerator/latest/install/install-guide.md
  content-accelerator/latest/install/java-support.md
  content-accelerator/latest/install/upgrading.md
  content-accelerator/latest/support/index.md
Labels: next release :arrow_right:

#1048 [DOCS-7210] Update Teams 2.0 Supported Platforms
  microsoft-teams/latest/support/index.md
Labels: next release :arrow_right:

#1029 [DOCS-7184] Content Services Community 7.4
  content-services/community/admin/audit.md
  content-services/community/admin/content-stores.md
  content-services/community/admin/import-transfer.md
  content-services/community/admin/index.md
  content-services/community/admin/security.md
  content-services/community/admin/troubleshoot.md
  content-services/community/config/file-servers.md
  content-services/community/config/index.md
  content-services/community/config/repository.md
  content-services/community/install/containers/docker-compose.md
  content-services/community/install/containers/index.md
  content-services/community/upgrade/index.md
  content-services/latest/config/file-servers.md
Labels: next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#1054 [DOCS-7287] Add Recent Files feature
  desktop-sync/latest/index.md
  desktop-sync/latest/support/index.md
  desktop-sync/latest/using/app-menu.md
Labels: next release :arrow_right:

#1057 [DOCS-7253] Update Supported platforms for Sync Service 3.10
  sync-service/latest/admin/monitor/index.md
  sync-service/latest/support/index.md
Labels: next release :arrow_right:

#1059 [DOCS-7273] Update release versions for Transform Service 3.0
  transform-service/latest/config/index.md
  transform-service/latest/install/index.md
Labels: next release :arrow_right:

#1060 [DOCS-7275] Update Control Center to version 8.1
  content-services/latest/install/containers/docker-compose.md
Labels: next release :arrow_right:

#1055 [DOCS-7251][DOCS-7286] Add Desktop Sync 1.16 compatibility with ACS
  content-services/7.2/support/index.md
  content-services/7.3/support/index.md
  content-services/latest/support/index.md
Labels: next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#1061 [DOCS-7254] Update Alfresco Content Connector for Salesforce 2.4.1
  salesforce/latest/install/index.md
Labels: next release :arrow_right:

#1064 [DOCS-7209] Fix Teams 1.1 ACS 7.3 support
  content-services/7.1/support/index.md
  microsoft-teams/1.1/support/index.md
Labels: next release :arrow_right:

#1065 [DOCS-7167] Update AIS 1.5 supported platforms
  intelligence-services/1.4/support/index.md
  intelligence-services/latest/support/index.md
Labels: next release :arrow_right:

#1066 [DOCS-7212] Fix MS 365 Connector 2.0 compatibility with ACS
  microsoft-365/latest/support/index.md
Labels: next release :arrow_right:

#1067 [DOCS-7298] Add link to Mutual TLS page and fix app name
  content-services/community/install/containers/index.md
  content-services/latest/release/index.md
Labels: next release :arrow_right:
