Repository Alfresco/docs-alfresco, pull requests merged in 2023-07, with the labels that each got.

#1069 [DOCS-7037] Move AEV section in Docs site config file
  _config.yml
Labels: next release :arrow_right:

#1072 [DOCS-7285] Update Content Services 7.4 Supported platforms page
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1037 [DOCS-7261] Ansible install for ACS 7.4
  content-services/latest/install/ansible.md
Labels: next release :arrow_right:

#1068 ACS-4369 Support for path features.
  search-enterprise/latest/using/unsupported.md
Labels: next release :arrow_right:

#1046 [DOCS-7000] Add Folder rule information
  _data/toc/digital-workspace.yaml
  digital-workspace/latest/using/index.md
Labels: DO NOT MERGE 🙅🏻‍♂️

#1076 [DOCS-7054] Mobile Workspace 1.7 Custom URL
  mobile-workspace/latest/using/index.md
Labels: next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️
