Repository Alfresco/docs-alfresco, pull requests merged in 2023-02, with the labels that each got.

#919 [DOCS-7002] Correct redirects from Admin Console docs links
  redirects/7.0/concepts/auth-alfrescontlm-intro.html
  redirects/7.0/concepts/auth-alfrescontlm-props.html
  redirects/7.1/concepts/auth-alfrescontlm-intro.html
  redirects/7.1/concepts/auth-alfrescontlm-props.html
  redirects/7.2/concepts/auth-alfrescontlm-intro.html
  redirects/7.2/concepts/auth-alfrescontlm-props.html
  redirects/7.3/concepts/auth-alfrescontlm-intro.html
  redirects/7.3/concepts/auth-alfrescontlm-props.html
  redirects/7.3/concepts/elasticsearch-overview.html
Labels: PR: reviewed-approved

#912 [DOCS 7045] Alfresco Content Services 7.3 Install with Ansible updates
  content-services/latest/install/ansible.md
Labels: PR: reviewed-approved, PR: partially-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#921 [DOCS-7110] Remove trailing space in redirect path
  redirects/7.3/concepts/auth-alfrescontlm-intro.html
Labels: PR: reviewed-approved

#923 [DOCS-6415] Improve description for uploading empty folders in Share
  content-services/latest/using/content/manage.md
Labels: PR: reviewed-approved

#924 [DOCS-7059] Add transactional information
  process-automation/latest/admin/release.md
Labels: PR: reviewed-approved

#928 [DOCS-7107] Remove leftover content from SSO Guide for ACS 7.3 and above
  identity-service/latest/tutorial/sso/ldap.md
  identity-service/latest/tutorial/sso/saml.md
Labels: PR: reviewed-approved

#926 [DOCS-5866] Process Services Update overriding the Default logback.xml file
  process-services/1.9/admin/index.md
  process-services/2.0/admin/index.md
  process-services/2.1/admin/index.md
  process-services/2.2/admin/index.md
  process-services/latest/admin/index.md
Labels: PR: reviewed-approved

#929 [DOCS-6950] Fix link to SSO Guide for SAML 1.2
  saml-module/latest/index.md
Labels: PR: reviewed-approved

#933 [DOCS-6545] Add Search in multi-value fields
  insight-engine/1.1/using/sql/syntax.md
  insight-engine/1.4/using/sql/syntax.md
  insight-engine/latest/using/sql/syntax.md
  search-enterprise/3.0/using/index.md
  search-enterprise/3.1/using/index.md
  search-enterprise/latest/using/index.md
  search-services/1.3/using/index.md
  search-services/1.4/using/index.md
  search-services/latest/using/index.md
Labels: PR: partially-approved

#935 [DOCS-6953] Add/correct parameters
  search-enterprise/latest/config/index.md
Labels: PR: partially-approved

#922 [DOCS-6862] Alfresco Mobile Workspace terminology updates
  mobile-workspace/latest/using/index.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#920 [DOCS-7090] Add delete option
  process-automation/latest/admin/monitor.md
Labels: PR: reviewed-approved

#931 [DOCS-6680] Add Edit user task notification
  process-automation/latest/model/processes/index.md
Labels: PR: reviewed-approved
