Repository Alfresco/docs-alfresco, pull requests merged in 2023-03, with the labels that each got.

#938 [DOCS-7093] Add Process History
  digital-workspace/images/process-history.png
  digital-workspace/latest/process/managing.md
Labels: PR: reviewed-approved

#936 [DOCS-7137] Update keys
  search-services/latest/config/keys.md
Labels: PR: reviewed-approved, tracked, DO NOT MERGE 🙅🏻‍♂️

#941 [DOCS-4594] Remove reference to AWS instance type in DTE docs
  content-services/5.2/install/index.md
  transformation-engine/2.2/install/index.md
  transformation-engine/latest/install/index.md
Labels: PR: reviewed-approved

#943 [DOCS-5422] Clarify supported MS Office file types in DTE docs
  content-services/5.2/install/index.md
  transformation-engine/2.2/index.md
  transformation-engine/latest/index.md
Labels: PR: reviewed-approved

#940 [DOCS-7098] Outlook Integration - Improve description for Simple Search Filter
  microsoft-outlook/latest/using/index.md
Labels: PR: reviewed-approved

#942 [DOCS-7073] Add trustedOrigin configuration for Salesforce Communities
  salesforce/latest/config/index.md
Labels: PR: reviewed-approved

#937 [MNT-23282] APS Asterisk note with Editor tab
  process-services/latest/using/process/app-designer.md
Labels: PR: reviewed-approved

#945 [DOCS-7071] Add instructions to configure AIS to work with APS
  identity-service/latest/config/index.md
  process-services/latest/config/authenticate.md
Labels: PR: reviewed-approved

#939 [DOCS-7095] Add Edit Process Permissions
  process-automation/latest/model/processes/index.md
Labels: PR: partially-approved, DO NOT MERGE 🙅🏻‍♂️

#359 [DOCS-6392] Set mutual TLS solr.secureComms=
  insight-engine/1.0/install/options.md
  insight-engine/1.1/install/options.md
  insight-engine/1.4/install/options.md
  insight-engine/latest/install/options.md
  search-services/1.3/install/options.md
  search-services/1.4/install/options.md
Labels: PR: reviewed-approved, search-sie

#930 [DOCS-7092] Add User Tasks and Service Tasks
  process-automation/latest/admin/monitor.md
Labels: PR: reviewed-approved

#374 [DOCS-6399] Align SP for APS and IDS
  identity-service/1.0/support/index.md
  identity-service/1.1/support/index.md
  identity-service/1.2/support/index.md
  identity-service/1.3/support/index.md
  identity-service/1.4/support/index.md
  process-services/1.9/support/index.md
  process-services/latest/support/index.md
Labels: PR: partially-approved

#656 [DOCS-6628] - Add theme information
  process-automation/images/ADW-colors.png
  process-automation/latest/model/interfaces.md
Labels: PR: partially-approved, DO NOT MERGE 🙅🏻‍♂️

#948 [DOCS-7070] Correct ADW version in Identity Service 1.7 docs
  identity-service/1.7/support/index.md
Labels: PR: partially-approved

#949 [DOCS-7031] Fix Supported platforms page for Identity Service 1.8
  identity-service/latest/support/index.md
Labels: PR: partially-approved

#946 [DOCS-7145] Added Offline Search
  mobile-workspace/latest/using/index.md
Labels: question, PR: unreviewed, PR: draft, PR: partially-approved

#950 [DOCS-7183] Correct Delete/Audit option
  process-automation/latest/admin/monitor.md
Labels: PR: unreviewed
