Repository Alfresco/docs-alfresco, pull requests merged in 2023-01, with the labels that each got.

#900 [DOCS-7053] Insight Engine version bump to 2.0.6
  insight-engine/latest/support/index.md
  insight-engine/latest/using/index.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#901 [DOCS-7052] Search Services version bump to 2.0.6
  search-services/latest/support/index.md
Labels: PR: reviewed-approved

#902 [DOCS-7030] Alfresco Content Services 7.3 Enterprise Trial updates
  content-services/latest/install/containers/docker-compose.md
Labels: documentation, PR: unreviewed, PR: reviewed-approved, PR: reviewed-changes-requested, PR: partially-approved, DO NOT MERGE 🙅🏻‍♂️

#905 [DOCS-7036] Improve Repository - JavaScript Execution section
  content-services/6.2/config/repository.md
  content-services/7.0/config/repository.md
  content-services/7.1/config/repository.md
  content-services/7.2/config/repository.md
  content-services/latest/config/repository.md
Labels: documentation, PR: unreviewed, PR: reviewed-approved, PR: partially-approved, DO NOT MERGE 🙅🏻‍♂️

#907 [DOCS-7079] Add new ACS version
  intelligence-services/latest/support/index.md
Labels: documentation, PR: unreviewed, PR: reviewed-approved, PR: partially-approved, DO NOT MERGE 🙅🏻‍♂️

#913 [DOCS-7049] Update upgrade path
  process-services/latest/upgrade/index.md
Labels: PR: partially-approved

#911 [DOCS-7008] Add Desktop Sync 1.14 compatibility in Content Services docs
  content-services/7.2/support/index.md
  content-services/latest/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#916 [DOCS-6952][DOCS-6696] Update Federation Services compatibility with Content Services
  content-services/7.0/support/index.md
  content-services/7.1/support/index.md
  content-services/7.2/support/index.md
Labels: PR: partially-approved, next release :arrow_right:

#892 [DOCS-6947] Alfresco Outlook Integration 2.9.2
  microsoft-outlook/images/2-9-2-outlook-sidebar-annotated.png
  microsoft-outlook/latest/config/index.md
  microsoft-outlook/latest/install/index.md
  microsoft-outlook/latest/support/index.md
  microsoft-outlook/latest/using/index.md
Labels: PR: reviewed-approved, next release :arrow_right:

#917 [DOCS-7078] Content Services 7.3.1 New JavaScript Execution section
  content-services/latest/release/index.md
Labels: PR: partially-approved, next release :arrow_right:

#909 [DOCS-7009] Add new Search feature for Mac & Windows
  desktop-sync/images/ds-ico-search.png
  desktop-sync/images/ds-system-menu-1.14.png
  desktop-sync/latest/index.md
  desktop-sync/latest/using/app-menu.md
Labels: PR: partially-approved, next release :arrow_right:

#918 [DOCS 7061] Alfresco Content Services 7.3.1
  content-services/7.0/support/index.md
  content-services/7.1/support/index.md
  content-services/7.2/support/index.md
  content-services/latest/config/repository.md
  content-services/latest/release/index.md
  content-services/latest/support/index.md
Labels: PR: reviewed-approved, next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️
