Repository Alfresco/docs-alfresco, pull requests merged in 2024-01, with the labels that each got.

#1232 [DOCS-7502] Correct https error in link
  search-enterprise/latest/using/languages.md
Labels: tracked

#1193 [DOCS-7504] Update manual.md
  process-services/latest/install/manual.md
Labels: tracked

#1266 [DOCS-7469] Improved clarity between Release and Version
  process-automation/latest/admin/monitor.md
  process-automation/latest/admin/release.md
Labels: PR: unreviewed

#1263 [DOCS-6697] Corrected MacOS shortcut
  process-automation/latest/using/index.md
Labels: bug

#1206 [DOCS-7468] Development Configuration variables
  process-automation/latest/admin/release.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#1204 [DOCS-7459] Creating Custom UI template
  process-automation/latest/model/interfaces.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#1202 [DOCS-7458] Deployment progress tracing
  process-automation/latest/admin/release.md
Labels: PR: reviewed-approved, DO NOT MERGE 🙅🏻‍♂️

#1272 [DOCS-7494] Update release summary
  microsoft-outlook/latest/index.md
Labels: next release :arrow_right:

#1275 [DOCS-7495] Update Admin page to include switch to SAML SSO
  microsoft-outlook/images/2-10-Outlook-connection-saml.png
  microsoft-outlook/latest/admin/index.md
Labels: next release :arrow_right:

#1125 [DOCS-7342] Installation and configuration changes for Outlook Integration 2.10
  microsoft-outlook/latest/config/index.md
  microsoft-outlook/latest/index.md
  microsoft-outlook/latest/install/index.md
  microsoft-outlook/latest/upgrade/index.md
  microsoft-outlook/latest/using/index.md
Labels: next release :arrow_right:

#1281 [DOCS-7152] UI change to ADW
  digital-workspace/4.0/index.md
Labels: next release :arrow_right:

#1268 [DOCS-7527] Typo in DTE Config index.md
  transformation-engine/latest/config/index.md
Labels: tracked

#1287 [DOCS-7016] Fix Release Dates in AGS
  governance-services/7.2/install/docker.md
  governance-services/7.2/install/uninstall.md
  governance-services/7.3/install/docker.md
  governance-services/7.3/install/uninstall.md
  governance-services/7.4/install/docker.md
  governance-services/7.4/install/uninstall.md
  governance-services/latest/install/docker.md
Labels: next release :arrow_right:

#1277 [DOCS-7531] Add Postgresql JDBC for ACS 23.1
  content-services/latest/support/index.md
Labels: tracked

#1278 [DOCS-7306] Add Outlook Integration 2.10 compatibility with ACS 7.4
  content-services/7.4/support/index.md
Labels: next release :arrow_right:

#1284 [DOCS-7314] Add Desktop Sync 1.17 compatibility with ACS
  content-services/7.2/support/index.md
  content-services/7.3/support/index.md
  content-services/7.4/support/index.md
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1290 [DOCS-7514] Update Supported Platforms pages for ActiveMQ CVE-2023-46604
  content-services/7.1/support/index.md
  content-services/7.2/support/index.md
  content-services/7.3/support/index.md
  content-services/7.4/support/index.md
  transform-service/2.1/support/index.md
Labels: next release :arrow_right:

#1289 [DOCS-7097] Move Control Center - Security Controls from ADW to ACS docs
  _data/toc/digital-workspace.yaml
  content-services/7.4/admin/control-center.md
  content-services/latest/admin/control-center.md
  digital-workspace/4.0/governance/security.md
  digital-workspace/4.1/governance/security.md
  digital-workspace/4.2/governance/security.md
  digital-workspace/latest/governance/security.md
Labels: next release :arrow_right:

#1259 [DOCS-7525] Update index.md
  search-services/latest/using/index.md
Labels: tracked

#1283 [DOCS-7313] Release and maintenance updates for Desktop Sync 1.17
  desktop-sync/1.12/admin/index.md
  desktop-sync/1.13/admin/index.md
  desktop-sync/1.14/admin/index.md
  desktop-sync/1.15/admin/index.md
  desktop-sync/1.16/admin/index.md
  desktop-sync/images/conflict-1.17.png
  desktop-sync/images/conflict-resolution-1.17.png
  desktop-sync/images/conflict-resolution-mac-1.17.png
  desktop-sync/images/ds-properties-view-mac2-1.17.png
  desktop-sync/images/ds-properties-view-win-1.17.png
  desktop-sync/images/ds-share-file-1.17.png
  desktop-sync/images/ds-share-file-mac-1.17.png
  desktop-sync/images/ds-tabbed-ui-1.17.png
  desktop-sync/images/initialsync-mac-1.17.png
  desktop-sync/images/setup-1.17.png
  desktop-sync/latest/admin/index.md
  desktop-sync/latest/config/index.md
  desktop-sync/latest/index.md
  desktop-sync/latest/install/index.md
  desktop-sync/latest/support/index.md
  desktop-sync/latest/using/app-icons.md
  desktop-sync/latest/using/app-menu.md
  desktop-sync/latest/using/faq.md
  desktop-sync/latest/using/metadata.md
  desktop-sync/latest/using/select-to-sync.md
  desktop-sync/latest/using/sharing.md
  desktop-sync/latest/using/sync-conflict-guide.md
Labels: next release :arrow_right:
