Repository Alfresco/docs-alfresco, pull requests merged in 2024-02, with the labels that each got.

#1321 [DOCS-7575] Fix/keycloak compatibility
  content-services/7.4/support/index.md
  content-services/latest/support/index.md
Labels: tracked

#1228 [DOCS-7503] Change alfresco-acs-java-rest-api new naming
  content-services/latest/develop/oop-sdk.md
Labels: tracked

#1317 [DOCS-7573] Custom UI is now uploaded with Modeling app
  process-automation/latest/develop/index.md
Labels: next release :arrow_right:

#1114 [DOCS-7372] Support Case 01623221 - Update Hazelcast Share Cluster example configuration SchemaLocation
  content-services/7.2/admin/cluster.md
Labels: tracked

#1318 [DOCS-7565] Updated development of Custom UI
  process-automation/latest/develop/index.md
Labels: next release :arrow_right:

#1331 [DOCS-7578] Add configuration for Document Transformation Engine 2.4.2
  transformation-engine/latest/config/index.md
Labels: next release :arrow_right:

#1332 [DOCS-7583] Drop secret key from adw example json config
  identity-service/latest/tutorial/sso/ldap.md
  identity-service/latest/tutorial/sso/saml.md
Labels: tracked

#1338 Add secured parameter for INCOMING_WEBHOOK
  process-automation/latest/model/triggers.md
Labels: DO NOT MERGE 🙅🏻‍♂️

#1302 [DOCS-7441] Update Supported Platforms for Alfresco Enterprise Viewer…
  content-services/latest/support/index.md
  enterprise-viewer/latest/support/index.md
  search-enterprise/latest/support/index.md
  search-services/latest/support/index.md
Labels: next release :arrow_right:
