Repository Alfresco/docs-alfresco, pull requests merged in 2024-03, with the labels that each got.

#1353 [DOCS-7603] AGS 23.02 Update docs for Azure WORM feature
  _data/toc/governance-services.yaml
  governance-services/latest/install/docker.md
  governance-services/latest/support/index.md
  governance-services/latest/using/azure-worm.md
  governance-services/latest/using/worm.md
Labels: next release :arrow_right:

#1361 [DOCS-7550] Add Control Center 8.4 compatibility for ACS 23
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1348 [DOCS-7558] Alfresco Governance Services 23.2
  _config.yml
  _data/toc/governance-services.yaml
  governance-services/latest/develop/index.md
  governance-services/latest/install/docker.md
  governance-services/latest/install/zip.md
  governance-services/latest/support/index.md
  governance-services/latest/upgrade/index.md
  governance-services/latest/using/azure-worm.md
  governance-services/latest/using/worm.md
Labels: next release :arrow_right:

#1347 [DOCS-7587] Update Supported Platforms page for Transform Service 4.1
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1354 [DOCS-7439] Update supported platforms for Alfresco Content Accelerator 4.0
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1365 [DOCS-7592] Add compatibility for SAP Applications Connector 6.0.1 with ACS
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1363 [DOCS-7605] Alfresco Content Accelerator Autofile criteriaRegexes update
  content-accelerator/3.5/configure/autofile.md
  content-accelerator/3.6/configure/autofile.md
  content-accelerator/latest/configure/autofile.md
Labels: next release :arrow_right:

#1373 [DOCS-7587] Add ATS 4.0 compatibility back into ACS 23.1 table
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1374 [DOCS-7600] Fix AIS compatibility for ACS 23.x
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1364 [DOCS-7591] Update supported platforms for Alfresco Content Connector for SAP Applications 6.0.1
  sap/latest/support/index.md
Labels: next release :arrow_right:

#1378 [DOCS-7614] Update information for Wizard Admin installation Content Accelerator 4.0
  content-accelerator/latest/install/install-guide.md
  content-accelerator/latest/install/installation-requirements.md
Labels: next release :arrow_right:

#1375 [DOCS-7530] Add Federation Services 3.1 compatibility for ACS 23.x
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1377 [DOCS-7577][DOCS-7444] Add Alfresco SDK 4.x compatibility
  content-services/7.4/support/index.md
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1379 [DOCS-7536] Update Supported Platforms for SAP Cloud Connector 2.0
  content-services/7.4/support/index.md
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1380 [DOCS-7586] Update Supported Platforms for AWS S3 Connector 6.1
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1382 [DOCS-7581] Update Supported Platforms for Google Docs Integration 4.1
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1345 [DOCS-7561] Update Alfresco Content Services Support Platforms 23.2
  content-services/7.4/support/index.md
  content-services/latest/support/index.md
Labels: next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#1386 [DOCS-7615] Fix ACS and AGS Tutorials TOC links
  _data/toc/content-services-tutorial.yaml
  _data/toc/governance-services-tutorial.yaml
Labels: next release :arrow_right:

#1389 [DOCS-7524] Add APS to ACS support page
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1390 [DOCS-7608] Add new LDAP property
  process-services/latest/config/authenticate.md
Labels: next release :arrow_right:

#1394 [DOCS-7491] Update SDK compatibility with ACS 23.x
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1392 [DOCS-7607] Alfresco Content Connector for Azure - Add new property to configure endpoints
  microsoft-azure/latest/config/index.md
Labels: next release :arrow_right:

#1395 [DOCS-7623] Update Support pages for ACS and ADW
  content-services/7.1/support/index.md
  content-services/7.2/support/index.md
  content-services/7.3/support/index.md
  content-services/7.4/support/index.md
  content-services/latest/support/index.md
  digital-workspace/4.3/support/index.md
  digital-workspace/latest/support/index.md
Labels: next release :arrow_right:

#1346 [DOCS-7595] Update Upgrade page
  process-services/latest/support/index.md
  process-services/latest/upgrade/index.md
Labels: next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#1398 [DOCS-7553] Add Alfresco Extension Inspector 2.0 in ACS 23.x
  content-services/latest/develop/extension-inspector.md
Labels: next release :arrow_right:

#1396 [DOCS-7624] Update Supported Platforms in Search modules
  content-services/7.1/support/index.md
  insight-engine/latest/support/index.md
  search-enterprise/3.1/support/index.md
  search-enterprise/3.2/support/index.md
  search-enterprise/3.3/support/index.md
  search-enterprise/latest/support/index.md
  search-services/latest/support/index.md
Labels: next release :arrow_right:

#1399 [DOCS-7510] Add Keycloak config to ACS 7.3 - ACS 23.x docs
  _data/toc/content-services.yaml
  content-services/7.3/config/keycloak.md
  content-services/7.4/config/keycloak.md
  content-services/images/keycloak-master-realm.png
  content-services/latest/config/keycloak.md
Labels: next release :arrow_right:

#1404 [DOCS-7602] Configuration changes for Alfresco Content Connector for SAP Cloud 1.2
  sap-cloud/images/sap_oact_soffdb_soffhttp_category_to_default.png
  sap-cloud/images/sap_skpr08_map_category_to_soffdb.png
  sap-cloud/latest/config/index.md
Labels: next release :arrow_right:

#1410 [DOCS-7602] Configuration changes for Alfresco Content Connector for SAP Cloud 1.2
  sap-cloud/1.2/config/index.md
Labels: next release :arrow_right:

#1403 [DOCS-7114] Update remote partitioning commands for Search Enterprise
  search-enterprise/3.2/admin/index.md
  search-enterprise/3.3/admin/index.md
  search-enterprise/latest/admin/index.md
Labels: DO NOT MERGE 🙅🏻‍♂️

#1371 [DOCS-7579] Add Multiple Salesforce Orgs feature
  salesforce/images/sf-manage-consumer-details.png
  salesforce/latest/index.md
  salesforce/latest/install/index.md
Labels: next release :arrow_right:

#1405 [DOCS-7377] Alfresco Content Services - set ADW as the recommended app in the Install section
  content-services/latest/install/ansible.md
  content-services/latest/install/containers/docker-compose.md
  content-services/latest/install/containers/helm-examples.md
Labels: DO NOT MERGE 🙅🏻‍♂️

#1412 [DOCS-6156] Update default value of alfresco.index.transformContent
  search-services/1.3/config/properties.md
  search-services/1.4/config/properties.md
  search-services/latest/config/properties.md
Labels: DO NOT MERGE 🙅🏻‍♂️
