Repository Alfresco/docs-alfresco, pull requests merged in 2024-04, with the labels that each got.

#1421 [DOCS-7617] Update AGS Community files
  governance-services/community/develop/index.md
  governance-services/community/install/docker.md
  governance-services/community/install/uninstall.md
  governance-services/community/install/zip.md
Labels: next release :arrow_right:

#1413 [DOCS-5990] Update Full Text Search for negation
  search-services/1.3/using/index.md
  search-services/1.4/using/index.md
  search-services/latest/using/index.md
Labels: DO NOT MERGE 🙅🏻‍♂️

#1271 [DOCS-7526] Update breaking-changes-1.x.md
  search-services/latest/upgrade/breaking-changes-1.x.md
Labels: tracked

#1438 [DOCS-7618] Update APS 2.4.x docs to include LDAP property
  process-services/2.4/config/authenticate.md
Labels: next release :arrow_right:

#1439 [DOCS-7613] Make suggested changes for ADW 4.4 and 4.3
  digital-workspace/4.3/develop/deploy.md
  digital-workspace/4.3/develop/manage.md
  digital-workspace/latest/develop/deploy.md
  digital-workspace/latest/develop/manage.md
Labels: next release :arrow_right:

#1300 [DOCS-7443] Add Alfresco Content Services SDK 4.7 and 4.8 docs
  _data/toc/content-services.yaml
  content-services/latest/develop/sdk.md
Labels: next release :arrow_right:

#1449 [DOCS-7648] Add AIS 3.1.1 to ACS 7.4.2 Supported Platforms
  content-services/7.4/support/index.md
Labels: next release :arrow_right:

#1456 [DOCS-7678] Add Windows 11 compatibility for ACS 23.x
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1453 [DOCS-7658] Add Alfresco Sync Service 5.0 to ACS 23.x Supported platforms
  content-services/latest/support/index.md
Labels: next release :arrow_right:

#1446 [DOCS-7635] Update Supported Platforms for Search Enterprise
  search-enterprise/3.2/support/index.md
  search-enterprise/3.3/support/index.md
  search-enterprise/latest/support/index.md
Labels: next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#1455 [DOCS-7650] Add Connector for Azure 3.2.1 to ACS Supported Platforms
  content-services/7.4/support/index.md
  content-services/latest/support/index.md
Labels: next release :arrow_right:, DO NOT MERGE 🙅🏻‍♂️

#1452 [DOCS-7651] Update Microsoft Teams 2.0.x Supported Platforms
  microsoft-teams/latest/support/index.md
Labels: next release :arrow_right:

#1448 [DOCS-7645] Update Supported Platforms page for Alfresco Transform Service 4.1.1
  transform-service/latest/support/index.md
Labels: next release :arrow_right:

#1457 [DOCS-7657] Decoupling updates for Sync Service 5.0
  sync-service/latest/admin/faq.md
  sync-service/latest/admin/index.md
  sync-service/latest/admin/monitor/index.md
  sync-service/latest/admin/troubleshoot.md
  sync-service/latest/index.md
  sync-service/latest/install/options.md
Labels: next release :arrow_right:

#1451 [DOCS-7660] Update Supported Platforms page for APS 24.2
  process-services/latest/support/index.md
Labels: next release :arrow_right:

#1433 [DOCS-7659] Alfresco Process Services 24.2 docs
  _config.yml
  _data/toc/process-services.yaml
  process-services/latest/support/index.md
Labels: next release :arrow_right:

#1430 [DOCS-7628] Update ACS Supported Platforms page for 7.4.2 Release
  content-services/7.4/support/index.md
  content-services/latest/support/index.md
  transform-service/latest/support/index.md
Labels: next release :arrow_right:

#1460 [DOCS-7443] Fix code block and text formatting in SDK 4 page
  content-services/latest/develop/sdk.md
Labels: next release :arrow_right:

#1463 [DOCS-7633] Update docs for Alfresco Outlook Integration 2.9.3
  microsoft-outlook/2.9/install/index.md
  microsoft-outlook/2.9/support/index.md
Labels: next release :arrow_right:
